package com.o2o.carpooling.notification.chat;

import com.o2o.carpooling.common.domain.OrderStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.InMemoryFixedWindowRateLimiter;
import feign.Request;
import feign.FeignException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import(ChatRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class ChatServiceTest {

    private static final String RIDER = "user-13800000001";
    private static final String DRIVER = "user-13800000002";
    private static final String STRANGER = "user-13800000099";
    private static final String ORDER = "order-1";
    private static final String TRIP = "trip-1";

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private ChatRepository repository;

    private final MutableClock clock = new MutableClock(Instant.parse("2026-07-01T00:00:00Z"));
    private final FakeOrderClient orderClient = new FakeOrderClient();
    private final FakeTripClient tripClient = new FakeTripClient();
    private ChatService service;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists chat_messages").update();
        jdbcClient.sql("drop table if exists chat_conversations").update();
        jdbcClient.sql("""
            create table chat_conversations (
              id bigint generated by default as identity primary key,
              conversation_id varchar(64) not null unique,
              order_id varchar(64) not null unique,
              trip_id varchar(64) not null,
              driver_id varchar(64) not null,
              rider_id varchar(64) not null,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              status varchar(16) not null,
              driver_last_read_id bigint not null default 0,
              rider_last_read_id bigint not null default 0,
              last_message_at timestamp(3),
              last_message_preview varchar(120),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null
            )
            """).update();
        jdbcClient.sql("""
            create table chat_messages (
              id bigint generated by default as identity primary key,
              message_id varchar(64) not null unique,
              conversation_id varchar(64) not null,
              sender_id varchar(64) not null,
              body varchar(500) not null,
              client_msg_id varchar(64) not null,
              created_at timestamp(3) not null,
              unique (conversation_id, sender_id, client_msg_id)
            )
            """).update();
        orderClient.orders.clear();
        orderClient.orders.put(ORDER, new OrderFeignClient.OrderInfo(ORDER, TRIP, RIDER, 2, OrderStatus.SEAT_LOCKED));
        tripClient.trips.clear();
        tripClient.trips.put(TRIP, new TripFeignClient.TripInfo(TRIP, DRIVER, "软件园三期", "集美大学"));
        service = new ChatService(repository, orderClient, tripClient,
            new InMemoryFixedWindowRateLimiter(clock), clock);
    }

    /* ---- membership / discovery ---- */

    @Test
    void riderAndDriverShareTheSameConversationForAnOrder() {
        ChatRepository.Conversation byRider = service.openForOrder(RIDER, ORDER);
        ChatRepository.Conversation byDriver = service.openForOrder(DRIVER, ORDER);

        assertThat(byDriver.conversationId()).isEqualTo(byRider.conversationId());
        assertThat(byRider.driverId()).isEqualTo(DRIVER);
        assertThat(byRider.riderId()).isEqualTo(RIDER);
    }

    @Test
    void strangerGets404OnEveryEndpoint() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);
        service.send(RIDER, conversation.conversationId(), "c-1", "你好");

        assertNotFound(() -> service.openForOrder(STRANGER, ORDER));
        assertNotFound(() -> service.messages(STRANGER, conversation.conversationId(), null, 30));
        assertNotFound(() -> service.send(STRANGER, conversation.conversationId(), "c-x", "hi"));
        assertNotFound(() -> service.markRead(STRANGER, conversation.conversationId(), null));
        // An operator role header does not change the outcome: chat has no operator surface.
        assertNotFound(() -> service.messages("user-operator", conversation.conversationId(), null, 30));
        // Listing shows nothing to non-participants.
        assertThat(service.listForUser(STRANGER, 20)).isEmpty();
    }

    @Test
    void unknownOrderAndUnknownConversationAreIndistinguishableFrom403() {
        assertNotFound(() -> service.openForOrder(RIDER, "order-missing"));
        assertNotFound(() -> service.messages(RIDER, "conv-missing", null, 30));
    }

    @Test
    void cancelledOrderCannotOpenAConversation() {
        orderClient.orders.put(ORDER, new OrderFeignClient.OrderInfo(ORDER, TRIP, RIDER, 2, OrderStatus.USER_CANCELLED));

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.openForOrder(RIDER, ORDER))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("CONVERSATION_UNAVAILABLE"));
    }

    /* ---- messaging ---- */

    @Test
    void sendReceiveMarkReadAndUnreadCountsWork() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);
        service.send(RIDER, conversation.conversationId(), "c-1", "师傅您好，我在东门等您");
        service.send(DRIVER, conversation.conversationId(), "c-2", "好的，马上到");

        assertThat(service.unreadCount(DRIVER)).isEqualTo(1);
        assertThat(service.unreadCount(RIDER)).isEqualTo(1);

        List<ChatRepository.Message> forDriver = service.messages(DRIVER, conversation.conversationId(), null, 30);
        assertThat(forDriver).hasSize(2);
        assertThat(forDriver.get(0).body()).isEqualTo("师傅您好，我在东门等您");

        service.markRead(DRIVER, conversation.conversationId(), null);
        assertThat(service.unreadCount(DRIVER)).isZero();
        // The rider's unread is untouched by the driver's read.
        assertThat(service.unreadCount(RIDER)).isEqualTo(1);
    }

    @Test
    void sendIsIdempotentPerClientMsgId() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);

        ChatRepository.Message first = service.send(RIDER, conversation.conversationId(), "retry-1", "第一次");
        ChatRepository.Message replay = service.send(RIDER, conversation.conversationId(), "retry-1", "第一次");

        assertThat(replay.messageId()).isEqualTo(first.messageId());
        assertThat(service.messages(RIDER, conversation.conversationId(), null, 30)).hasSize(1);
    }

    @Test
    void olderMessagesPageByKeyset() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);
        for (int i = 1; i <= 5; i++) {
            service.send(RIDER, conversation.conversationId(), "c-" + i, "消息 " + i);
        }

        List<ChatRepository.Message> latest = service.messages(RIDER, conversation.conversationId(), null, 2);
        assertThat(latest).extracting(ChatRepository.Message::body).containsExactly("消息 4", "消息 5");
        List<ChatRepository.Message> older = service.messages(RIDER, conversation.conversationId(), latest.get(0).cursor(), 2);
        assertThat(older).extracting(ChatRepository.Message::body).containsExactly("消息 2", "消息 3");
    }

    /* ---- validation + abuse protection ---- */

    @Test
    void rejectsEmptyOversizedAndControlCharacterBodies() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);

        assertErrorCode(() -> service.send(RIDER, conversation.conversationId(), "c-1", "   "), "CHAT_MESSAGE_EMPTY");
        assertErrorCode(() -> service.send(RIDER, conversation.conversationId(), "c-2", "长".repeat(501)), "CHAT_MESSAGE_TOO_LONG");
        assertErrorCode(() -> service.send(RIDER, conversation.conversationId(), "c-3", "hi\u0007there"), "CHAT_MESSAGE_INVALID");
        assertErrorCode(() -> service.send(RIDER, conversation.conversationId(), "", "hello"), "CHAT_CLIENT_MSG_ID_INVALID");
        // Newlines are ordinary chat content.
        assertThatCode(() -> service.send(RIDER, conversation.conversationId(), "c-4", "第一行\n第二行"))
            .doesNotThrowAnyException();
    }

    @Test
    void sendIsRateLimitedPerUser() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);
        for (int i = 0; i < 20; i++) {
            service.send(RIDER, conversation.conversationId(), "flood-" + i, "消息 " + i);
        }

        assertErrorCode(() -> service.send(RIDER, conversation.conversationId(), "flood-final", "再来一条"),
            "CHAT_RATE_LIMITED");
        // The driver's budget is separate.
        assertThatCode(() -> service.send(DRIVER, conversation.conversationId(), "d-1", "收到"))
            .doesNotThrowAnyException();
    }

    @Test
    void sendIsRefusedOnceTheOrderIsCancelled() {
        ChatRepository.Conversation conversation = service.openForOrder(RIDER, ORDER);
        service.send(RIDER, conversation.conversationId(), "c-1", "你好");

        orderClient.orders.put(ORDER, new OrderFeignClient.OrderInfo(ORDER, TRIP, RIDER, 2, OrderStatus.DRIVER_CANCELLED));
        clock.advance(Duration.ofSeconds(61)); // expire the 60s order-status cache

        assertErrorCode(() -> service.send(RIDER, conversation.conversationId(), "c-2", "还在吗"),
            "CONVERSATION_UNAVAILABLE");
        // History stays readable after cancellation.
        assertThat(service.messages(RIDER, conversation.conversationId(), null, 30)).hasSize(1);
    }

    /* ---- helpers ---- */

    private void assertNotFound(Runnable call) {
        assertErrorCode(call, "CONVERSATION_NOT_FOUND");
    }

    private void assertErrorCode(Runnable call, String errorCode) {
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(call::run)
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo(errorCode));
    }

    private static final class FakeOrderClient implements OrderFeignClient {
        final Map<String, OrderInfo> orders = new HashMap<>();

        @Override
        public OrderInfo order(String orderId) {
            OrderInfo order = orders.get(orderId);
            if (order == null) {
                throw notFound("/internal/orders/" + orderId);
            }
            return order;
        }
    }

    private static final class FakeTripClient implements TripFeignClient {
        final Map<String, TripInfo> trips = new HashMap<>();

        @Override
        public TripInfo trip(String tripId) {
            TripInfo trip = trips.get(tripId);
            if (trip == null) {
                throw notFound("/api/trips/" + tripId);
            }
            return trip;
        }
    }

    private static FeignException.NotFound notFound(String path) {
        Request request = Request.create(Request.HttpMethod.GET, path, Map.of(), null,
            StandardCharsets.UTF_8, null);
        return new FeignException.NotFound("not found", request, null, Map.of());
    }

    private static final class MutableClock extends Clock {
        private Instant instant;

        private MutableClock(Instant instant) {
            this.instant = instant;
        }

        private void advance(Duration duration) {
            this.instant = this.instant.plus(duration);
        }

        @Override
        public Instant instant() {
            return instant;
        }

        @Override
        public ZoneId getZone() {
            return ZoneOffset.UTC;
        }

        @Override
        public Clock withZone(ZoneId zone) {
            return this;
        }
    }
}
