package com.o2o.carpooling.identity;

import com.o2o.carpooling.common.domain.IdentityVerificationStatus;
import com.o2o.carpooling.common.domain.LivenessCheckStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.ProviderProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import(IdentityVerificationRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class IdentityVerificationServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private IdentityVerificationRepository repository;

    private final Clock clock = Clock.fixed(NOW, ZoneOffset.UTC);
    private final RecordingNotification notification = new RecordingNotification();

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists identity_verifications").update();
        jdbcClient.sql("""
            create table identity_verifications (
              id bigint generated by default as identity primary key,
              verification_id varchar(64) not null unique,
              user_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              status varchar(32) not null,
              liveness_status varchar(32) not null,
              provider varchar(32) not null,
              provider_ref varchar(120),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              constraint uk_identity_user_idem unique (user_id, idempotency_key)
            )
            """).update();
    }

    @Test
    void startsSessionPendingWithConfiguredProvider() {
        IdentityVerification verification = service("demo").start("user-1", "张三", "110101199001011234", "key-1");

        assertThat(verification.status()).isEqualTo(IdentityVerificationStatus.PENDING);
        assertThat(verification.livenessStatus()).isEqualTo(LivenessCheckStatus.PENDING);
        assertThat(verification.provider()).isEqualTo("demo");
        // The outcome is never delivered at start time.
        assertThat(notification.requests).isEmpty();
    }

    @Test
    void isIdempotentPerUserAndKey() {
        IdentityVerificationService service = service("demo");

        IdentityVerification first = service.start("user-1", "张三", "1101", "key-1");
        IdentityVerification second = service.start("user-1", "张三", "1101", "key-1");

        assertThat(second.verificationId()).isEqualTo(first.verificationId());
    }

    @Test
    void failsClosedWhenProviderUnconfigured() {
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service("aliyun").start("user-1", "张三", "1101", "key-1"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("IDENTITY_PROVIDER_UNCONFIGURED"));
    }

    @Test
    void getIsOwnerScoped() {
        IdentityVerificationService service = service("demo");
        IdentityVerification verification = service.start("user-1", "张三", "1101", "key-1");

        assertThat(service.get(verification.verificationId(), "user-1").verificationId()).isEqualTo(verification.verificationId());
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.get(verification.verificationId(), "intruder"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("IDENTITY_FORBIDDEN"));
    }

    @Test
    void approvalRequiresPassedLiveness() {
        IdentityVerificationService service = service("demo");
        IdentityVerification verification = service.start("user-1", "张三", "1101", "key-1");

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.applySessionOutcome(verification.verificationId(), IdentityVerificationStatus.APPROVED))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("IDENTITY_LIVENESS_REQUIRED"));
    }

    @Test
    void livenessPassThenApproveDeliversResultToInbox() {
        IdentityVerificationService service = service("demo");
        IdentityVerification verification = service.start("user-1", "张三", "1101", "key-1");

        service.applyLivenessOutcome(verification.verificationId(), LivenessCheckStatus.PASSED);
        IdentityVerification approved = service.applySessionOutcome(verification.verificationId(), IdentityVerificationStatus.APPROVED);

        assertThat(approved.status()).isEqualTo(IdentityVerificationStatus.APPROVED);
        assertThat(approved.livenessStatus()).isEqualTo(LivenessCheckStatus.PASSED);
        assertThat(notification.requests).hasSize(1);
        assertThat(notification.requests.get(0).category()).isEqualTo("IDENTITY_VERIFICATION_RESULT");
        assertThat(notification.requests.get(0).userId()).isEqualTo("user-1");
    }

    @Test
    void rejectDeliversResult() {
        IdentityVerificationService service = service("demo");
        IdentityVerification verification = service.start("user-1", "张三", "1101", "key-1");

        IdentityVerification rejected = service.applySessionOutcome(verification.verificationId(), IdentityVerificationStatus.REJECTED);

        assertThat(rejected.status()).isEqualTo(IdentityVerificationStatus.REJECTED);
        assertThat(notification.requests).hasSize(1);
    }

    @Test
    void isUserApprovedReflectsApprovedSessions() {
        IdentityVerificationService service = service("demo");
        IdentityVerification verification = service.start("user-1", "张三", "1101", "key-1");

        assertThat(service.isUserApproved("user-1")).isFalse();
        assertThat(service.isUserApproved("")).isFalse();

        service.applyLivenessOutcome(verification.verificationId(), LivenessCheckStatus.PASSED);
        service.applySessionOutcome(verification.verificationId(), IdentityVerificationStatus.APPROVED);

        assertThat(service.isUserApproved("user-1")).isTrue();
        assertThat(service.isUserApproved("someone-else")).isFalse();
    }

    @Test
    void illegalTransitionAfterTerminalIsRejected() {
        IdentityVerificationService service = service("demo");
        IdentityVerification verification = service.start("user-1", "张三", "1101", "key-1");
        service.applySessionOutcome(verification.verificationId(), IdentityVerificationStatus.REJECTED);

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.applySessionOutcome(verification.verificationId(), IdentityVerificationStatus.APPROVED))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("IDENTITY_ILLEGAL_TRANSITION"));
    }

    private IdentityVerificationService service(String providerType) {
        ProviderProperties providerProperties = new ProviderProperties();
        providerProperties.getIdentity().setType(providerType);
        return new IdentityVerificationService(
            repository,
            List.of(new DemoIdentityProvider()),
            providerProperties,
            notification,
            clock);
    }

    private static final class RecordingNotification implements NotificationFeignClient {
        private final List<NotifyRequest> requests = new ArrayList<>();

        @Override
        public void notify(NotifyRequest request) {
            requests.add(request);
        }
    }
}
