package com.o2o.carpooling.common.domain;

/**
 * Where a trip came from. {@code DEMO} trips are generated by the demo virtual-trip feature
 * (demo profile only) and are labelled as demo data in the UI; they never impersonate real users.
 */
public enum TripSource {
    USER,
    DEMO
}
