package com.o2o.carpooling.ai;

import com.o2o.carpooling.common.domain.OcrResult;
import com.o2o.carpooling.common.domain.OcrTask;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({OcrTaskRepository.class, OcrService.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OcrServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OcrTaskRepository repository;

    @Autowired
    private OcrService service;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists ocr_tasks").update();
        jdbcClient.sql("""
            create table ocr_tasks (
              id bigint generated by default as identity primary key,
              task_id varchar(64) not null unique,
              file_object_id varchar(64) not null,
              result_json clob not null,
              completed_at timestamp(3) not null
            )
            """).update();
    }

    @Test
    void persistsMockOcrTaskWithMaskedSensitiveFields() {
        OcrResult result = service.inspectMock("file-driving-license-001");

        OcrTask task = repository.findLatestByFileObjectId("file-driving-license-001").orElseThrow();
        String rawResultJson = jdbcClient.sql("select result_json from ocr_tasks where task_id = :taskId")
            .param("taskId", task.taskId())
            .query(String.class)
            .single();

        assertThat(result.provider()).isEqualTo("mock-ocr");
        assertThat(task.fileObjectId()).isEqualTo("file-driving-license-001");
        assertThat(task.result().fields().get("licenseNo")).doesNotContain("MOCK-");
        assertThat(rawResultJson).contains("mock-ocr").doesNotContain("MOCK-");
    }
}
