package com.o2o.carpooling.ai;

import com.o2o.carpooling.common.domain.OcrResult;
import com.o2o.carpooling.common.domain.OcrTask;
import com.o2o.carpooling.common.domain.OcrTaskStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.ProviderProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import(OcrTaskRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OcrServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OcrTaskRepository repository;

    private final Clock clock = Clock.fixed(NOW, ZoneOffset.UTC);

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists ocr_tasks").update();
        jdbcClient.sql("""
            create table ocr_tasks (
              id bigint generated by default as identity primary key,
              task_id varchar(64) not null unique,
              file_object_id varchar(64) not null,
              status varchar(32) not null,
              provider_ref varchar(120),
              result_json clob,
              submitted_at timestamp(3) not null,
              completed_at timestamp(3)
            )
            """).update();
    }

    @Test
    void inspectMockCompletesTaskWithMaskedSensitiveFields() {
        OcrResult result = service("demo").inspectMock("file-driving-license-001");

        OcrTask task = repository.findLatestByFileObjectId("file-driving-license-001").orElseThrow();
        String rawResultJson = jdbcClient.sql("select result_json from ocr_tasks where task_id = :taskId")
            .param("taskId", task.taskId())
            .query(String.class)
            .single();

        assertThat(result.provider()).isEqualTo("mock-ocr");
        assertThat(task.status()).isEqualTo(OcrTaskStatus.COMPLETED);
        assertThat(task.result().fields().get("licenseNo")).doesNotContain("MOCK-");
        assertThat(rawResultJson).contains("mock-ocr").doesNotContain("MOCK-");
    }

    @Test
    void submitCreatesProcessingTaskThenGetCompletes() {
        OcrService service = service("demo");

        OcrTask submitted = service.submit("file-1");
        assertThat(submitted.status()).isEqualTo(OcrTaskStatus.PROCESSING);
        assertThat(submitted.result()).isNull();

        OcrTask completed = service.get(submitted.taskId());
        assertThat(completed.status()).isEqualTo(OcrTaskStatus.COMPLETED);
        assertThat(completed.result()).isNotNull();
        assertThat(completed.completedAt()).isEqualTo(NOW);
    }

    @Test
    void failsClosedWhenProviderUnconfigured() {
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service("aliyun").submit("file-1"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("OCR_PROVIDER_UNCONFIGURED"));
    }

    @Test
    void listRecentReturnsNewestTasksFirst() {
        OcrService service = service("demo");
        OcrTask first = service.submit("file-1");
        OcrTask second = service.submit("file-2");

        List<OcrTask> recent = service.listRecent(10);

        assertThat(recent).extracting(OcrTask::taskId).containsExactly(second.taskId(), first.taskId());
    }

    private OcrService service(String providerType) {
        ProviderProperties providerProperties = new ProviderProperties();
        providerProperties.getOcr().setType(providerType);
        return new OcrService(repository, List.of(new DemoOcrProvider()), providerProperties, clock);
    }
}
