package com.o2o.carpooling.notification;

import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest
@Import(NotificationDeliveryRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class NotificationServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private NotificationDeliveryRepository repository;

    private final Clock clock = Clock.fixed(NOW, ZoneOffset.UTC);

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists notification_deliveries").update();
        jdbcClient.sql("""
            create table notification_deliveries (
              id bigint generated by default as identity primary key,
              delivery_id varchar(64) not null unique,
              user_id varchar(64) not null,
              channel varchar(16) not null,
              category varchar(48) not null,
              title varchar(160) not null,
              masked_preview varchar(255) not null,
              revealable_payload varchar(512),
              reveal_expires_at timestamp(3),
              status varchar(16) not null,
              correlation_id varchar(64),
              retry_count int not null default 0,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              read_at timestamp(3)
            )
            """).update();
    }

    @Test
    void demoNotifyPersistsMaskedRecordButKeepsPayloadRevealableWithinTtl() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));

        DeliveryReceipt receipt = service.notify(new NotificationMessage(
            "user-1", ChannelType.SMS, "AUTH_SMS_CODE", "登录验证码",
            "您的验证码为 123456，5分钟内有效", "123456", Duration.ofMinutes(5), "trace-1"));

        assertThat(receipt.status()).isEqualTo(DeliveryStatus.DELIVERED);
        DeliveryRecord stored = repository.findByDeliveryIdAndUserId(receipt.deliveryId(), "user-1").orElseThrow();
        assertThat(stored.maskedPreview()).doesNotContain("123456").contains("•");
        assertThat(repository.findRevealablePayload(receipt.deliveryId(), "user-1", NOW)).contains("123456");
    }

    @Test
    void revealIsDeniedAfterTtl() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        DeliveryReceipt receipt = service.notify(new NotificationMessage(
            "user-1", ChannelType.SMS, "AUTH_SMS_CODE", "登录验证码",
            "您的验证码为 654321", "654321", Duration.ofMinutes(5), "trace-2"));

        assertThat(repository.findRevealablePayload(receipt.deliveryId(), "user-1", NOW.plus(Duration.ofMinutes(6)))).isEmpty();
    }

    @Test
    void inboxIsScopedToRecipient() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        service.notify(message("user-1"));
        service.notify(message("user-2"));

        assertThat(repository.findByUserId("user-1", 50)).hasSize(1);
        assertThat(repository.findByUserId("user-2", 50)).hasSize(1);
    }

    @Test
    void listRecentDeliveriesSpansUsersNewestFirstWithMaskedPreviewsOnly() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        service.notify(new NotificationMessage(
            "user-1", ChannelType.SMS, "AUTH_SMS_CODE", "登录验证码",
            "您的验证码为 222333", "222333", Duration.ofMinutes(5), "trace-l1"));
        DeliveryReceipt second = service.notify(message("user-2"));

        List<DeliveryRecord> recent = service.listRecentDeliveries(10);

        assertThat(recent).hasSize(2);
        assertThat(recent.get(0).deliveryId()).isEqualTo(second.deliveryId());
        assertThat(recent).extracting(DeliveryRecord::userId).containsExactly("user-2", "user-1");
        // The cross-user console listing must never leak the sensitive payload.
        assertThat(recent.get(1).maskedPreview()).doesNotContain("222333");
    }

    @Test
    void failsClosedWhenNoAdapterConfigured() {
        NotificationService service = service(List.of());

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.notify(message("user-1")))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("NOTIFICATION_PROVIDER_UNCONFIGURED"));
    }

    @Test
    void rejectsBlankRecipient() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        assertThatThrownBy(() -> service.notify(message("")))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void revealReturnsPayloadForOwnerAndRejectsOthers() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        DeliveryReceipt receipt = service.notify(new NotificationMessage(
            "user-1", ChannelType.SMS, "AUTH_SMS_CODE", "登录验证码",
            "您的验证码为 111111", "111111", Duration.ofMinutes(5), "trace-r"));

        assertThat(service.reveal("user-1", receipt.deliveryId())).isEqualTo("111111");
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.reveal("user-2", receipt.deliveryId()))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("DEMO_REVEAL_UNAVAILABLE"));
    }

    @Test
    void markReadSetsReadStatusForOwner() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        DeliveryReceipt receipt = service.notify(message("user-1"));

        assertThat(service.markRead("user-1", receipt.deliveryId())).isTrue();
        assertThat(repository.findByDeliveryIdAndUserId(receipt.deliveryId(), "user-1").orElseThrow().status())
            .isEqualTo(DeliveryStatus.READ);
    }

    @Test
    void operatorSimulateStatusUpdatesDelivery() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));
        DeliveryReceipt receipt = service.notify(message("user-1"));

        service.simulateStatus("operator-1", receipt.deliveryId(), DeliveryStatus.FAILED);

        assertThat(repository.findByDeliveryIdAndUserId(receipt.deliveryId(), "user-1").orElseThrow().status())
            .isEqualTo(DeliveryStatus.FAILED);
    }

    @Test
    void operatorSimulateStatusOnUnknownDeliveryFailsClosed() {
        NotificationService service = service(List.of(new DemoNotificationChannelAdapter()));

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.simulateStatus("operator-1", "ntf-missing", DeliveryStatus.DELIVERED))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("DELIVERY_NOT_FOUND"));
    }

    private NotificationService service(List<NotificationChannelAdapter> adapters) {
        return new NotificationService(adapters, repository, clock);
    }

    private NotificationMessage message(String userId) {
        return new NotificationMessage(userId, ChannelType.IN_APP, "PAYMENT_STATUS", "订单状态",
            "您的订单已支付成功", null, null, "trace-x");
    }
}
