package com.o2o.carpooling.payment;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.o2o.carpooling.common.domain.Money;
import com.o2o.carpooling.common.domain.OrderDetail;
import com.o2o.carpooling.common.domain.PaymentIntentStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import(PaymentIntentRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class DemoPaymentControlServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");
    private static final String SECRET = "unit-test-webhook-secret-not-a-real-one";
    private static final Duration TOLERANCE = Duration.ofMinutes(5);

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PaymentIntentRepository repository;

    private final ObjectMapper objectMapper = new ObjectMapper();
    private final Clock clock = Clock.fixed(NOW, ZoneOffset.UTC);
    private final StubOrderClient orderClient = new StubOrderClient();

    private DemoPaymentControlService controlService;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists payment_intents").update();
        jdbcClient.sql("drop table if exists payment_callback_events").update();
        jdbcClient.sql("""
            create table payment_intents (
              id bigint generated by default as identity primary key,
              intent_id varchar(64) not null unique,
              order_id varchar(64) not null,
              rider_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              amount decimal(12,2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              provider varchar(32) not null,
              provider_ref varchar(120),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              constraint uk_intent_order_idem unique (order_id, idempotency_key)
            )
            """).update();
        jdbcClient.sql("""
            create table payment_callback_events (
              id bigint generated by default as identity primary key,
              event_id varchar(80) not null unique,
              intent_id varchar(64) not null,
              outcome varchar(32) not null,
              received_at timestamp(3) not null
            )
            """).update();

        repository.save(new PaymentIntent(
            "pi-1", "order-1", "user-1", new Money(new BigDecimal("18.00"), "CNY"),
            PaymentIntentStatus.REQUIRES_PAYMENT, "demo", "demo-ref-pi-1", NOW, NOW), "key-1");

        PaymentCallbackVerifier verifier =
            new PaymentCallbackVerifier(SECRET, new InMemorySeenNonceStore(clock), TOLERANCE, clock);
        PaymentCallbackService callbackService =
            new PaymentCallbackService(repository, orderClient, objectMapper, clock);
        PaymentCallbackSigner signer = new PaymentCallbackSigner(SECRET, clock);
        controlService = new DemoPaymentControlService(repository, verifier, callbackService, signer, objectMapper);
    }

    @Test
    void normalSucceededDrivesIntentThroughSignedPipeline() {
        List<DemoPaymentControlService.CallbackEmission> emissions =
            controlService.simulate("pi-1", PaymentIntentStatus.SUCCEEDED, SimulationMode.NORMAL, 0);

        assertThat(emissions).hasSize(1);
        assertThat(emissions.get(0).accepted()).isTrue();
        assertThat(emissions.get(0).resultStatus()).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(controlService.currentStatus("pi-1")).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    @Test
    void duplicateModeIsIdempotent() {
        List<DemoPaymentControlService.CallbackEmission> emissions =
            controlService.simulate("pi-1", PaymentIntentStatus.SUCCEEDED, SimulationMode.DUPLICATE, 0);

        assertThat(emissions).hasSize(2);
        assertThat(emissions).extracting(DemoPaymentControlService.CallbackEmission::eventId)
            .containsExactly(emissions.get(0).eventId(), emissions.get(0).eventId()); // same event id twice
        assertThat(controlService.currentStatus("pi-1")).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    @Test
    void outOfOrderModeCannotOverrideTerminalState() {
        List<DemoPaymentControlService.CallbackEmission> emissions =
            controlService.simulate("pi-1", PaymentIntentStatus.SUCCEEDED, SimulationMode.OUT_OF_ORDER, 0);

        assertThat(emissions).hasSize(2);
        assertThat(emissions.get(1).outcome()).isEqualTo(PaymentIntentStatus.FAILED);
        assertThat(controlService.currentStatus("pi-1")).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    @Test
    void delayBeyondToleranceIsRejectedByThePipeline() {
        List<DemoPaymentControlService.CallbackEmission> emissions =
            controlService.simulate("pi-1", PaymentIntentStatus.SUCCEEDED, SimulationMode.NORMAL, 3600);

        assertThat(emissions).hasSize(1);
        assertThat(emissions.get(0).accepted()).isFalse();
        assertThat(emissions.get(0).rejectionCode()).isEqualTo("PAYMENT_CALLBACK_TIMESTAMP");
        assertThat(controlService.currentStatus("pi-1")).isEqualTo(PaymentIntentStatus.REQUIRES_PAYMENT);
        assertThat(orderClient.markPaidCalls.get()).isZero();
    }

    @Test
    void rejectsNonTerminalOutcome() {
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> controlService.simulate("pi-1", PaymentIntentStatus.REQUIRES_PAYMENT, SimulationMode.NORMAL, 0))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("PAYMENT_CALLBACK_OUTCOME_INVALID"));
    }

    @Test
    void rejectsUnknownIntent() {
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> controlService.simulate("pi-unknown", PaymentIntentStatus.SUCCEEDED, SimulationMode.NORMAL, 0))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("PAYMENT_INTENT_NOT_FOUND"));
    }

    private final class StubOrderClient implements OrderClient {
        private final AtomicInteger markPaidCalls = new AtomicInteger();

        @Override
        public Optional<OrderDetail> findOrder(String orderId) {
            return Optional.empty();
        }

        @Override
        public OrderDetail markPaid(String orderId) {
            markPaidCalls.incrementAndGet();
            return null;
        }
    }
}
