package com.o2o.carpooling.payment;

import com.o2o.carpooling.common.domain.Money;
import com.o2o.carpooling.common.domain.OrderDetail;
import com.o2o.carpooling.common.domain.OrderStatus;
import com.o2o.carpooling.common.domain.PaymentIntentStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.ProviderProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import(PaymentIntentRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class PaymentIntentServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PaymentIntentRepository repository;

    private final OrderDetail order = new OrderDetail(
        "order-1", "trip-1", "user-1", 1, new Money(new BigDecimal("18.00"), "CNY"), OrderStatus.PENDING_PAYMENT, NOW);

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists payment_intents").update();
        jdbcClient.sql("""
            create table payment_intents (
              id bigint generated by default as identity primary key,
              intent_id varchar(64) not null unique,
              order_id varchar(64) not null,
              rider_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              amount decimal(12,2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              provider varchar(32) not null,
              provider_ref varchar(120),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              constraint uk_intent_order_idem unique (order_id, idempotency_key)
            )
            """).update();
    }

    @Test
    void createsIntentInRequiresPaymentWithServerAmount() {
        PaymentIntentService service = service("demo");

        PaymentIntent intent = service.createIntent("user-1", "order-1", "key-1");

        assertThat(intent.status()).isEqualTo(PaymentIntentStatus.REQUIRES_PAYMENT);
        assertThat(intent.amount().amount()).isEqualByComparingTo("18.00");
        assertThat(intent.provider()).isEqualTo("demo");
    }

    @Test
    void isIdempotentPerOrderAndKey() {
        PaymentIntentService service = service("demo");

        PaymentIntent first = service.createIntent("user-1", "order-1", "key-1");
        PaymentIntent second = service.createIntent("user-1", "order-1", "key-1");

        assertThat(second.intentId()).isEqualTo(first.intentId());
    }

    @Test
    void rejectsPaymentByNonOwner() {
        PaymentIntentService service = service("demo");

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.createIntent("intruder", "order-1", "key-1"))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("PAYMENT_FORBIDDEN"));
    }

    @Test
    void failsClosedWhenProviderTypeHasNoAdapter() {
        PaymentIntentService service = service("stripe"); // no stripe adapter wired

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.createIntent("user-1", "order-1", "key-1"))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("PAYMENT_PROVIDER_UNCONFIGURED"));
    }

    private PaymentIntentService service(String providerType) {
        ProviderProperties providerProperties = new ProviderProperties();
        providerProperties.getPayment().setType(providerType);
        return new PaymentIntentService(
            repository,
            new StubOrderClient(),
            List.of(new DemoPaymentProvider()),
            providerProperties,
            Clock.fixed(NOW, ZoneOffset.UTC));
    }

    private final class StubOrderClient implements OrderClient {
        @Override
        public Optional<OrderDetail> findOrder(String orderId) {
            return "order-1".equals(orderId) ? Optional.of(order) : Optional.empty();
        }

        @Override
        public OrderDetail markPaid(String orderId) {
            return order;
        }
    }
}
