package com.o2o.carpooling.payment;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.o2o.carpooling.common.domain.Money;
import com.o2o.carpooling.common.domain.OrderDetail;
import com.o2o.carpooling.common.domain.PaymentIntentStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import(PaymentIntentRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class PaymentCallbackServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");
    private static final String SECRET = "unit-test-webhook-secret-not-a-real-one";
    private static final Duration TOLERANCE = Duration.ofMinutes(5);

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PaymentIntentRepository repository;

    private final ObjectMapper objectMapper = new ObjectMapper();
    private final Clock clock = Clock.fixed(NOW, ZoneOffset.UTC);
    private final StubOrderClient orderClient = new StubOrderClient();

    private PaymentCallbackVerifier verifier;
    private PaymentCallbackService service;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists payment_intents").update();
        jdbcClient.sql("drop table if exists payment_callback_events").update();
        jdbcClient.sql("""
            create table payment_intents (
              id bigint generated by default as identity primary key,
              intent_id varchar(64) not null unique,
              order_id varchar(64) not null,
              rider_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              amount decimal(12,2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              provider varchar(32) not null,
              provider_ref varchar(120),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              constraint uk_intent_order_idem unique (order_id, idempotency_key)
            )
            """).update();
        jdbcClient.sql("""
            create table payment_callback_events (
              id bigint generated by default as identity primary key,
              event_id varchar(80) not null unique,
              intent_id varchar(64) not null,
              outcome varchar(32) not null,
              received_at timestamp(3) not null
            )
            """).update();

        repository.save(new PaymentIntent(
            "pi-1", "order-1", "user-1", new Money(new BigDecimal("18.00"), "CNY"),
            PaymentIntentStatus.REQUIRES_PAYMENT, "demo", "demo-ref-pi-1", NOW, NOW), "key-1");

        verifier = new PaymentCallbackVerifier(SECRET, new InMemorySeenNonceStore(clock), TOLERANCE, clock);
        service = new PaymentCallbackService(repository, orderClient, objectMapper, clock);
    }

    @Test
    void succeededCallbackMovesIntentToSucceededAndMarksOrderPaid() {
        PaymentIntent result = deliver("evt-1", "pi-1", "SUCCEEDED", "nonce-1");

        assertThat(result.status()).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    @Test
    void rejectsForgedSignature() {
        String body = body("evt-1", "pi-1", "SUCCEEDED");
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> verifier.verify("demo", String.valueOf(NOW.getEpochSecond()), "nonce-1", "deadbeef", body))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("PAYMENT_CALLBACK_SIGNATURE_INVALID"));

        assertThat(status("pi-1")).isEqualTo(PaymentIntentStatus.REQUIRES_PAYMENT);
        assertThat(orderClient.markPaidCalls.get()).isZero();
    }

    @Test
    void rejectsReplayedNonce() {
        deliver("evt-1", "pi-1", "SUCCEEDED", "nonce-1");

        // Same nonce again (a distinct, correctly-signed event) must be refused as a replay.
        String body = body("evt-2", "pi-1", "FAILED");
        String ts = String.valueOf(NOW.getEpochSecond());
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> verifier.verify("demo", ts, "nonce-1", sign(ts, "nonce-1", body), body))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("PAYMENT_CALLBACK_REPLAY"));
    }

    @Test
    void isIdempotentForDuplicateEventId() {
        deliver("evt-1", "pi-1", "SUCCEEDED", "nonce-1");
        // Same event id, fresh nonce (so it passes replay) — must be an idempotent no-op.
        PaymentIntent second = deliver("evt-1", "pi-1", "SUCCEEDED", "nonce-2");

        assertThat(second.status()).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    @Test
    void ignoresConflictingOutcomeAfterTerminalState() {
        deliver("evt-1", "pi-1", "SUCCEEDED", "nonce-1");
        // A later, out-of-order FAILED callback must never resurrect a terminal intent.
        PaymentIntent afterFailed = deliver("evt-2", "pi-1", "FAILED", "nonce-2");

        assertThat(afterFailed.status()).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    @Test
    void rejectsStaleTimestampOutsideTolerance() {
        String body = body("evt-1", "pi-1", "SUCCEEDED");
        String staleTs = String.valueOf(NOW.minus(Duration.ofHours(1)).getEpochSecond());
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> verifier.verify("demo", staleTs, "nonce-1", sign(staleTs, "nonce-1", body), body))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("PAYMENT_CALLBACK_TIMESTAMP"));
    }

    @Test
    void failsClosedWhenWebhookSecretMissing() {
        PaymentCallbackVerifier unconfigured =
            new PaymentCallbackVerifier("", new InMemorySeenNonceStore(clock), TOLERANCE, clock);
        String body = body("evt-1", "pi-1", "SUCCEEDED");
        String ts = String.valueOf(NOW.getEpochSecond());
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> unconfigured.verify("demo", ts, "nonce-1", sign(ts, "nonce-1", body), body))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("PAYMENT_WEBHOOK_UNCONFIGURED"));
    }

    private PaymentIntent deliver(String eventId, String intentId, String outcome, String nonce) {
        String body = body(eventId, intentId, outcome);
        String ts = String.valueOf(NOW.getEpochSecond());
        verifier.verify("demo", ts, nonce, sign(ts, nonce, body), body);
        return service.apply(body);
    }

    private String body(String eventId, String intentId, String outcome) {
        Map<String, String> payload = new LinkedHashMap<>();
        payload.put("eventId", eventId);
        payload.put("intentId", intentId);
        payload.put("outcome", outcome);
        try {
            return objectMapper.writeValueAsString(payload);
        } catch (Exception exception) {
            throw new IllegalStateException(exception);
        }
    }

    private String sign(String timestamp, String nonce, String body) {
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(SECRET.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
            return HexFormat.of().formatHex(mac.doFinal((timestamp + "." + nonce + "." + body).getBytes(StandardCharsets.UTF_8)));
        } catch (Exception exception) {
            throw new IllegalStateException(exception);
        }
    }

    private PaymentIntentStatus status(String intentId) {
        return repository.findByIntentId(intentId).orElseThrow().status();
    }

    @Test
    void succeededCallbackRacingTimedOutOrderIsAcceptedAndLoggedForReconciliation() {
        // The order was timeout-cancelled before the provider's success arrived: order-service
        // refuses markPaid (translated to OrderPayConflictException). The webhook must still be
        // accepted — the intent is SUCCEEDED — instead of failing with a 5xx the PSP would retry.
        orderClient.failMarkPaidWithConflict = true;

        PaymentIntent result = deliver("evt-1", "pi-1", "SUCCEEDED", "nonce-1");

        assertThat(result.status()).isEqualTo(PaymentIntentStatus.SUCCEEDED);
        assertThat(orderClient.markPaidCalls.get()).isEqualTo(1);
    }

    private final class StubOrderClient implements OrderClient {
        private final AtomicInteger markPaidCalls = new AtomicInteger();
        private boolean failMarkPaidWithConflict;

        @Override
        public Optional<OrderDetail> findOrder(String orderId) {
            return Optional.empty();
        }

        @Override
        public OrderDetail markPaid(String orderId) {
            markPaidCalls.incrementAndGet();
            if (failMarkPaidWithConflict) {
                throw new OrderPayConflictException(orderId, null);
            }
            return null;
        }
    }
}
