package com.o2o.carpooling.payment;

import com.o2o.carpooling.common.domain.Money;
import com.o2o.carpooling.common.domain.OrderDetail;
import com.o2o.carpooling.common.domain.OrderStatus;
import com.o2o.carpooling.common.domain.PaymentSimulation;
import com.o2o.carpooling.common.domain.PaymentStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({PaymentSimulationRepository.class, PaymentSimulationService.class, PaymentSimulationServiceTest.FakeOrderClientConfig.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class PaymentSimulationServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PaymentSimulationService service;

    @Autowired
    private FakeOrderClient orderClient;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists payment_simulations").update();
        jdbcClient.sql("""
            create table payment_simulations (
              id bigint generated by default as identity primary key,
              payment_id varchar(64) not null unique,
              order_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              amount decimal(12, 2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              paid_at timestamp(3) not null,
              created_at timestamp(3) not null,
              unique (order_id, idempotency_key)
            )
            """).update();
        orderClient.reset();
    }

    @Test
    void simulatesSuccessUsingServerOrderAmountAndMarksOrderPaid() {
        PaymentSimulation payment = service.simulateSuccess(new SimulatePaymentCommand("order-001", "pay-idem-001"));

        assertThat(payment.status()).isEqualTo(PaymentStatus.SIMULATED_SUCCESS);
        assertThat(payment.amount().amount()).isEqualByComparingTo("28.20");
        assertThat(orderClient.markPaidCalls).isEqualTo(1);
    }

    @Test
    void replaysPaymentSimulationIdempotentlyWithoutMarkingOrderTwice() {
        PaymentSimulation first = service.simulateSuccess(new SimulatePaymentCommand("order-001", "pay-idem-001"));
        PaymentSimulation duplicate = service.simulateSuccess(new SimulatePaymentCommand("order-001", "pay-idem-001"));

        assertThat(duplicate.paymentId()).isEqualTo(first.paymentId());
        assertThat(orderClient.markPaidCalls).isEqualTo(1);
    }

    @Configuration
    static class FakeOrderClientConfig {
        @Bean
        FakeOrderClient fakeOrderClient() {
            return new FakeOrderClient();
        }

        @Bean
        OrderClient orderClient(FakeOrderClient fakeOrderClient) {
            return fakeOrderClient;
        }
    }

    static class FakeOrderClient implements OrderClient {
        int markPaidCalls;

        void reset() {
            markPaidCalls = 0;
        }

        @Override
        public Optional<OrderDetail> findOrder(String orderId) {
            return Optional.of(order());
        }

        @Override
        public OrderDetail markPaid(String orderId) {
            markPaidCalls++;
            return order();
        }

        private OrderDetail order() {
            return new OrderDetail(
                "order-001",
                "trip-001",
                "rider-001",
                1,
                new Money(new BigDecimal("28.20"), "CNY"),
                OrderStatus.PENDING_PAYMENT,
                Instant.parse("2026-06-23T11:00:00Z")
            );
        }
    }
}
