package com.o2o.carpooling.file;

import com.o2o.carpooling.common.domain.FileObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({FileObjectRepository.class, FileObjectService.class})
@TestPropertySource(properties = {
    "spring.flyway.enabled=false",
    "minio.bucket=driver-private"
})
class FileObjectServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private FileObjectRepository repository;

    @Autowired
    private FileObjectService service;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists file_objects").update();
        jdbcClient.sql("""
            create table file_objects (
              id bigint generated by default as identity primary key,
              file_id varchar(64) not null unique,
              owner_user_id varchar(64) not null,
              bucket varchar(128) not null,
              object_key varchar(512) not null,
              content_type varchar(120) not null,
              sha256 char(64) not null,
              visibility varchar(32) not null,
              created_at timestamp(3) not null
            )
            """).update();
    }

    @Test
    void createsPrivateFileMetadataForMockAndPresignFlows() {
        FileObject fileObject = service.createPrivateObject("user-001", "driver/license.png", "image/png");

        FileObject stored = repository.findByFileObjectId(fileObject.fileObjectId()).orElseThrow();
        String sha256 = jdbcClient.sql("select sha256 from file_objects where file_id = :fileId")
            .param("fileId", fileObject.fileObjectId())
            .query(String.class)
            .single();
        String visibility = jdbcClient.sql("select visibility from file_objects where file_id = :fileId")
            .param("fileId", fileObject.fileObjectId())
            .query(String.class)
            .single();

        assertThat(fileObject.fileObjectId()).startsWith("file-");
        assertThat(stored.ownerId()).isEqualTo("user-001");
        assertThat(stored.bucket()).isEqualTo("driver-private");
        assertThat(stored.privateObject()).isTrue();
        assertThat(sha256).hasSize(64);
        assertThat(visibility).isEqualTo("PRIVATE");
    }
}
