package com.o2o.carpooling.file;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Duration;
import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

@JdbcTest
@Import(FileAuditOutboxRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class FileAuditOutboxPublisherTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private FileAuditOutboxRepository repository;

    private FileAuditFeignClient auditFeignClient;
    private FileAuditOutboxPublisher publisher;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists file_audit_outbox").update();
        jdbcClient.sql("""
            create table file_audit_outbox (
              id bigint generated by default as identity primary key,
              event_id varchar(64) not null unique,
              audit_id varchar(64) not null,
              actor_id varchar(64) not null,
              action varchar(80) not null,
              target_type varchar(64) not null,
              target_id varchar(64) not null,
              metadata_json clob not null,
              status varchar(32) not null,
              attempts int not null,
              next_attempt_at timestamp(3) not null,
              last_error varchar(512),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              sent_at timestamp(3)
            )
            """).update();
        auditFeignClient = mock(FileAuditFeignClient.class);
        publisher = new FileAuditOutboxPublisher(repository, auditFeignClient);
    }

    @Test
    void deliversPendingAuditAndMarksSent() {
        Instant now = Instant.parse("2026-06-23T00:00:00Z");
        repository.enqueue("audit-1", "user-1", "FILE_UPLOAD_COMPLETED", "FILE", "file-1", "{\"objectKey\":\"k1\"}", now);

        int sent = publisher.publishDue(now.plusSeconds(1));

        assertThat(sent).isEqualTo(1);
        verify(auditFeignClient).append(any(AuditAppendRequest.class));
        assertThat(repository.findSendable(now.plus(Duration.ofHours(1)), 10)).isEmpty();
    }

    @Test
    void recordsFailureAndRetriesWhenDeliveryFails() {
        Instant now = Instant.parse("2026-06-23T00:00:00Z");
        repository.enqueue("audit-1", "user-1", "FILE_DOWNLOAD_PRESIGNED", "FILE", "file-1", "{}", now);
        doThrow(new RuntimeException("audit service down")).when(auditFeignClient).append(any(AuditAppendRequest.class));

        int sent = publisher.publishDue(now.plusSeconds(1));

        assertThat(sent).isZero();
        assertThat(repository.findSendable(now.plusSeconds(1), 10)).isEmpty();
        assertThat(repository.findSendable(now.plusSeconds(31), 10)).hasSize(1);
        assertThat(jdbcClient.sql("select attempts from file_audit_outbox").query(Integer.class).single()).isEqualTo(1);
    }
}
