package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.CoordinateDatum;
import com.o2o.carpooling.common.domain.GeoPoint;
import com.o2o.carpooling.common.domain.LocationRef;
import com.o2o.carpooling.common.domain.LocationSource;
import com.o2o.carpooling.common.domain.PricingPolicy;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.domain.TripSource;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.InMemoryFixedWindowRateLimiter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import({TripRepository.class, TripMatchingProperties.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class DemoTripGeneratorTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripRepository repository;

    @Autowired
    private TripMatchingProperties properties;

    private final FakeMapClient mapClient = new FakeMapClient();
    private DemoTripGenerator generator;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              idempotency_key varchar(80),
              origin_lat decimal(10,7), origin_lng decimal(10,7),
              destination_lat decimal(10,7), destination_lng decimal(10,7),
              coordinate_datum varchar(16),
              origin_adcode varchar(16), destination_adcode varchar(16),
              origin_city_code varchar(16), destination_city_code varchar(16),
              origin_place_id varchar(64), destination_place_id varchar(64),
              route_polyline clob,
              base_fare decimal(10,2), included_km decimal(7,3), per_km_fare decimal(10,2), min_fare decimal(10,2),
              source varchar(16) not null default 'USER'
            )
            """).update();
        mapClient.places.clear();
        mapClient.places.add(place("软件园三期", 24.4879, 118.1781, "350211"));
        mapClient.places.add(place("集美大学", 24.5766, 118.0994, "350211"));
        mapClient.places.add(place("厦门北站", 24.6153, 118.0507, "350211"));
        generator = new DemoTripGenerator(repository, mapClient,
            new InMemoryFixedWindowRateLimiter(Clock.fixed(NOW, ZoneOffset.UTC)), Clock.fixed(NOW, ZoneOffset.UTC));
    }

    private LocationRef place(String name, double lat, double lng, String adcode) {
        return new LocationRef(new GeoPoint(lat, lng, CoordinateDatum.GCJ02), "demo", "poi-" + name, "0592",
            adcode, name, name + "地址", LocationSource.DEMO_SEED, null, NOW);
    }

    @Test
    void generatesFiveDemoOffersLabelledAsDemoWithFormulaDrivenPricing() {
        List<TripOffer> offers = generator.generate("user-1",
            mapClient.places.get(0), mapClient.places.get(1), 42L);

        assertThat(offers).hasSize(5);
        assertThat(offers).allSatisfy(offer -> {
            assertThat(offer.source()).isEqualTo(TripSource.DEMO);
            assertThat(offer.driverId()).startsWith("demo-driver-");
        });
        // Synthetic drivers can never authenticate (auth only mints user-<phone>).
        assertThat(offers).extracting(TripOffer::driverId).doesNotContain("user-1");

        // Every offer's price equals the shared route priced by the SAME policy — zero variation.
        PricingPolicy policy = new PricingPolicy(
            properties.getPricing().getBaseFare(), properties.getPricing().getIncludedKm(),
            properties.getPricing().getPerKmFare(), properties.getPricing().getMinFare(),
            properties.getPricing().getCurrency());
        var expected = policy.quote(mapClient.lastRoute);
        assertThat(offers).allSatisfy(offer -> assertThat(offer.seatPrice()).isEqualTo(expected));
    }

    @Test
    void sameSeedProducesIdenticalOffers() {
        List<TripOffer> first = generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 7L);
        // Regenerate: replaces rather than accumulating.
        List<TripOffer> second = generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 7L);

        assertThat(second).hasSize(5);
        assertThat(offerShape(first)).isEqualTo(offerShape(second));
        // Replace-not-accumulate: still exactly 5 rows for these endpoints.
        assertThat(countDemoTrips()).isEqualTo(5);
    }

    @Test
    void regenerationReplacesRatherThanAccumulates() {
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 1L);
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 2L);
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 3L);

        assertThat(countDemoTrips()).isEqualTo(5);
    }

    @Test
    void randomRoutePicksTwoDistinctPlacesDeterministically() {
        List<TripOffer> a = generator.generateRandom("user-1", "0592", 99L);
        // Same seed → same endpoints.
        List<TripOffer> b = generator.generateRandom("user-1", "0592", 99L);

        assertThat(a.get(0).originText()).isNotEqualTo(a.get(0).destinationText());
        assertThat(a.get(0).originText()).isEqualTo(b.get(0).originText());
        assertThat(a.get(0).destinationText()).isEqualTo(b.get(0).destinationText());
    }

    @Test
    void generationIsRateLimitedPerUser() {
        for (int i = 0; i < 5; i++) {
            generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), (long) i);
        }
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 999L))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("DEMO_TRIP_RATE_LIMITED"));
    }

    @Test
    void expiredDemoTripCleanupRemovesOnlyPastDemoTrips() {
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 1L);
        // Move all demo departures far into the past.
        jdbcClient.sql("update trips set departure_at = {ts '2026-06-01 00:00:00'} where source = 'DEMO'").update();

        generator.cleanupExpiredDemoTrips();

        assertThat(countDemoTrips()).isZero();
    }

    private List<String> offerShape(List<TripOffer> offers) {
        return offers.stream()
            .map(offer -> offer.driverId() + "|" + offer.departureAt() + "|" + offer.inventory().totalSeats())
            .sorted()
            .toList();
    }

    private long countDemoTrips() {
        return jdbcClient.sql("select count(*) from trips where source = 'DEMO'").query(Long.class).single();
    }

    private static final class FakeMapClient implements MapClient {
        final List<LocationRef> places = new java.util.ArrayList<>();
        RouteSnapshot lastRoute;

        @Override
        public RouteSnapshot quoteRoute(String origin, String destination, String city) {
            throw new UnsupportedOperationException();
        }

        @Override
        public RouteSnapshot quoteRoute(LocationRef origin, LocationRef destination) {
            lastRoute = new RouteSnapshot("route-" + origin.displayName() + destination.displayName(),
                18_500, 2_100, "amap-mock",
                origin.point().toProviderLngLat() + ";" + destination.point().toProviderLngLat(),
                origin, destination);
            return lastRoute;
        }

        @Override
        public List<LocationRef> demoPlaces(String cityCode) {
            return places;
        }
    }
}
