package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.CoordinateDatum;
import com.o2o.carpooling.common.domain.GeoPoint;
import com.o2o.carpooling.common.domain.Haversine;
import com.o2o.carpooling.common.domain.LocationRef;
import com.o2o.carpooling.common.domain.LocationSource;
import com.o2o.carpooling.common.domain.PricingPolicy;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.domain.TripSource;
import com.o2o.carpooling.common.domain.TripStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.InMemoryFixedWindowRateLimiter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import({TripRepository.class, TripMatchingProperties.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class DemoTripGeneratorTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripRepository repository;

    @Autowired
    private TripMatchingProperties properties;

    private final FakeMapClient mapClient = new FakeMapClient();
    private DemoTripGenerator generator;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              idempotency_key varchar(80),
              origin_lat decimal(10,7), origin_lng decimal(10,7),
              destination_lat decimal(10,7), destination_lng decimal(10,7),
              coordinate_datum varchar(16),
              origin_adcode varchar(16), destination_adcode varchar(16),
              origin_city_code varchar(16), destination_city_code varchar(16),
              origin_place_id varchar(64), destination_place_id varchar(64),
              route_polyline clob,
              base_fare decimal(10,2), included_km decimal(7,3), per_km_fare decimal(10,2), min_fare decimal(10,2),
              source varchar(16) not null default 'USER'
            )
            """).update();
        mapClient.reset();
        // 厦门 places (same city). Real great-circle distances are used by the fake quote, so the
        // distance-range logic is exercised against realistic values.
        mapClient.addPlace("软件园三期", 24.4879, 118.1781, "350211", "0592");
        mapClient.addPlace("集美大学", 24.5766, 118.0994, "350211", "0592");
        mapClient.addPlace("厦门北站", 24.6153, 118.0507, "350211", "0592");
        generator = new DemoTripGenerator(repository, mapClient, properties,
            new InMemoryFixedWindowRateLimiter(Clock.fixed(NOW, ZoneOffset.UTC)), Clock.fixed(NOW, ZoneOffset.UTC));
    }

    @Test
    void generatesDemoOffersLabelledAsDemoWithFormulaDrivenPricing() {
        DemoTripGenerator.GeneratedDemoTrips result = generator.generate("user-1",
            mapClient.places.get(0), mapClient.places.get(1), 42L);

        assertThat(result.offers()).hasSize(properties.getDemo().getOffers());
        assertThat(result.offers()).allSatisfy(offer -> {
            assertThat(offer.source()).isEqualTo(TripSource.DEMO);
            assertThat(offer.driverId()).startsWith("demo-driver-");
        });
        assertThat(result.offers()).extracting(TripOffer::driverId).doesNotContain("user-1");

        PricingPolicy policy = new PricingPolicy(
            properties.getPricing().getBaseFare(), properties.getPricing().getIncludedKm(),
            properties.getPricing().getPerKmFare(), properties.getPricing().getMinFare(),
            properties.getPricing().getCurrency());
        var expected = policy.quote(result.route());
        assertThat(result.offers()).allSatisfy(offer -> assertThat(offer.seatPrice()).isEqualTo(expected));
    }

    @Test
    void generatedTripsAreReturnedByTheNormalTripSearchApi() {
        DemoTripGenerator.GeneratedDemoTrips result = generator.generate("user-1",
            mapClient.places.get(0), mapClient.places.get(1), 42L);

        // Search on the SAME endpoints (as the frontend does after generation) must return them.
        GeoPoint origin = result.origin().point();
        GeoPoint destination = result.destination().point();
        List<TripOffer> found = repository.searchByProximity(
            new TripSearchQuery(origin, destination, null, 1));

        assertThat(found).isNotEmpty();
        assertThat(found).allSatisfy(offer -> assertThat(offer.source()).isEqualTo(TripSource.DEMO));
        assertThat(found).extracting(TripOffer::tripId)
            .containsAll(result.offers().stream().map(TripOffer::tripId).toList());
    }

    @Test
    void generatedDeparturesFallInsideTheSearchTimeWindow() {
        DemoTripGenerator.GeneratedDemoTrips result = generator.generate("user-1",
            mapClient.places.get(0), mapClient.places.get(1), 42L);

        Instant windowEnd = NOW.plus(properties.getMatching().getDepartureWindow());
        assertThat(result.offers()).allSatisfy(offer -> {
            assertThat(offer.departureAt()).isAfterOrEqualTo(NOW);
            assertThat(offer.departureAt()).isBeforeOrEqualTo(windowEnd);
        });
    }

    @Test
    void sameSeedProducesIdenticalOffers() {
        var first = generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 7L).offers();
        var second = generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 7L).offers();

        assertThat(offerShape(first)).isEqualTo(offerShape(second));
        assertThat(countDemoTrips()).isEqualTo(properties.getDemo().getOffers());
    }

    @Test
    void regenerationReplacesRatherThanAccumulates() {
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 1L);
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 2L);
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 3L);

        assertThat(countDemoTrips()).isEqualTo(properties.getDemo().getOffers());
    }

    @Test
    void randomRoutePicksTwoDistinctSameCityPlacesDeterministicallyWithinRange() {
        DemoTripGenerator.GeneratedDemoTrips a = generator.generateRandom("user-1", "0592", 99L);
        DemoTripGenerator.GeneratedDemoTrips b = generator.generateRandom("user-1", "0592", 99L);

        assertThat(a.origin().displayName()).isNotEqualTo(a.destination().displayName());
        // Same seed → same endpoints (deterministic).
        assertThat(a.origin().displayName()).isEqualTo(b.origin().displayName());
        assertThat(a.destination().displayName()).isEqualTo(b.destination().displayName());
        // Same city, and distance within the configured range.
        assertThat(a.origin().cityCode()).isEqualTo(a.destination().cityCode());
        assertThat(a.route().distanceMeters()).isBetween(
            properties.getDemo().getMinDistanceMeters(), properties.getDemo().getMaxDistanceMeters());
        assertThat(a.offers()).hasSize(properties.getDemo().getOffers());
    }

    @Test
    void randomRouteWithoutCityChoosesOneCitySoEndpointsShareIt() {
        mapClient.addPlace("天府广场", 30.6570, 104.0657, "510105", "028");
        mapClient.addPlace("成都东站", 30.6300, 104.1414, "510108", "028");

        DemoTripGenerator.GeneratedDemoTrips result = generator.generateRandom("user-1", null, 5L);

        assertThat(result.origin().cityCode()).isEqualTo(result.destination().cityCode());
    }

    @Test
    void outOfRangePairsAreRetriedUntilAnInRangeRouteIsFound() {
        // First quote is far too short (below min); the generator must keep trying other pairs.
        mapClient.overrideFirstQuoteDistanceMeters = 300;

        DemoTripGenerator.GeneratedDemoTrips result = generator.generateRandom("user-1", "0592", 3L);

        assertThat(mapClient.quoteCount).isGreaterThan(1);
        assertThat(result.route().distanceMeters()).isBetween(
            properties.getDemo().getMinDistanceMeters(), properties.getDemo().getMaxDistanceMeters());
    }

    @Test
    void failsWithClearErrorWhenNoPairIsWithinRange() {
        // Force every quote out of range: no pair can ever qualify.
        mapClient.forceDistanceMeters = 500_000;

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> generator.generateRandom("user-1", "0592", 1L))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("DEMO_NO_VALID_ROUTE"));
        // Bounded: it did not loop forever.
        assertThat(mapClient.quoteCount).isLessThanOrEqualTo(properties.getDemo().getMaxAttempts());
    }

    @Test
    void tooFewPlacesInACityIsRejected() {
        mapClient.reset();
        mapClient.addPlace("孤点", 24.5, 118.1, "350211", "0592");

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> generator.generateRandom("user-1", "0592", 1L))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("DEMO_CITY_TOO_FEW_PLACES"));
    }

    @Test
    void generationIsRateLimitedPerUser() {
        for (int i = 0; i < 5; i++) {
            generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), (long) i);
        }
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 999L))
            .satisfies(exception -> assertThat(exception.errorCode()).isEqualTo("DEMO_TRIP_RATE_LIMITED"));
    }

    @Test
    void expiredDemoTripCleanupRemovesOnlyPastDemoTrips() {
        generator.generate("user-1", mapClient.places.get(0), mapClient.places.get(1), 1L);
        jdbcClient.sql("update trips set departure_at = {ts '2026-06-01 00:00:00'} where source = 'DEMO'").update();

        generator.cleanupExpiredDemoTrips();

        assertThat(countDemoTrips()).isZero();
    }

    private List<String> offerShape(List<TripOffer> offers) {
        return offers.stream()
            .map(offer -> offer.driverId() + "|" + offer.departureAt() + "|" + offer.inventory().totalSeats())
            .sorted()
            .toList();
    }

    private long countDemoTrips() {
        return jdbcClient.sql("select count(*) from trips where source = 'DEMO'").query(Long.class).single();
    }

    private static final class FakeMapClient implements MapClient {
        final List<LocationRef> places = new ArrayList<>();
        RouteSnapshot lastRoute;
        int quoteCount;
        Integer overrideFirstQuoteDistanceMeters;
        Integer forceDistanceMeters;

        void reset() {
            places.clear();
            lastRoute = null;
            quoteCount = 0;
            overrideFirstQuoteDistanceMeters = null;
            forceDistanceMeters = null;
        }

        void addPlace(String name, double lat, double lng, String adcode, String cityCode) {
            places.add(new LocationRef(new GeoPoint(lat, lng, CoordinateDatum.GCJ02), "demo",
                "poi-" + name, cityCode, adcode, name, name + "地址", LocationSource.DEMO_SEED, null, NOW));
        }

        @Override
        public RouteSnapshot quoteRoute(String origin, String destination, String city) {
            throw new UnsupportedOperationException();
        }

        @Override
        public RouteSnapshot quoteRoute(LocationRef origin, LocationRef destination) {
            quoteCount++;
            int distance;
            if (forceDistanceMeters != null) {
                distance = forceDistanceMeters;
            } else if (overrideFirstQuoteDistanceMeters != null && quoteCount == 1) {
                distance = overrideFirstQuoteDistanceMeters;
            } else {
                double straight = Haversine.distanceMeters(
                    origin.point().latitude(), origin.point().longitude(),
                    destination.point().latitude(), destination.point().longitude());
                distance = Math.max(500, (int) Math.round(straight * 1.3));
            }
            lastRoute = new RouteSnapshot("route-" + UUID.randomUUID(), distance,
                Math.max(120, distance / 8), "amap-mock",
                origin.point().toProviderLngLat() + ";" + destination.point().toProviderLngLat(),
                origin, destination);
            return lastRoute;
        }

        @Override
        public List<LocationRef> demoPlaces(String cityCode) {
            if (cityCode == null || cityCode.isBlank()) {
                return places;
            }
            return places.stream().filter(place -> cityCode.equals(place.cityCode())).toList();
        }
    }
}
