package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.CoordinateDatum;
import com.o2o.carpooling.common.domain.GeoPoint;
import com.o2o.carpooling.common.domain.Haversine;
import com.o2o.carpooling.common.domain.LocationRef;
import com.o2o.carpooling.common.domain.LocationSource;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.foundation.BusinessException;
import com.o2o.carpooling.common.foundation.InMemoryFixedWindowRateLimiter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Live driver location. The load-bearing assertions here are the authorization ones: a rider who
 * did not book the trip must not be able to locate its driver, and must not even learn that the
 * trip is being tracked.
 */
@JdbcTest
@Import({TripRepository.class, TripMatchingProperties.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class DriverLocationServiceTest {

    private static final Instant NOW = Instant.parse("2026-08-01T04:00:00Z");
    private static final GeoPoint SOFTWARE_PARK = GeoPoint.gcj02(24.4879, 118.1781);
    private static final GeoPoint JIMEI = GeoPoint.gcj02(24.5751, 118.0972);

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripRepository repository;

    @Autowired
    private TripMatchingProperties properties;

    private DriverLocationService service;
    private InMemoryDriverPresenceStore presenceStore;
    private MutableClock clock;
    private String tripId;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trip_seat_locks").update();
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique, driver_id varchar(64) not null,
              origin_text varchar(200) not null, destination_text varchar(200) not null,
              departure_at timestamp(3) not null, route_id varchar(64) not null,
              distance_meters int not null, duration_seconds int not null,
              route_provider varchar(64) not null, seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null, total_seats int not null,
              locked_seats int not null, status varchar(32) not null,
              created_at timestamp(3) not null, updated_at timestamp(3) not null, version int not null,
              idempotency_key varchar(80), origin_lat decimal(10,7), origin_lng decimal(10,7),
              destination_lat decimal(10,7), destination_lng decimal(10,7), coordinate_datum varchar(16),
              origin_adcode varchar(16), destination_adcode varchar(16), origin_city_code varchar(16),
              destination_city_code varchar(16), origin_place_id varchar(64),
              destination_place_id varchar(64), route_polyline clob,
              base_fare decimal(10,2), included_km decimal(7,3), per_km_fare decimal(10,2), min_fare decimal(10,2),
              source varchar(16) not null default 'USER'
            )
            """).update();
        jdbcClient.sql("""
            create table trip_seat_locks (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null, order_id varchar(64) not null unique,
              seats int not null, status varchar(32) not null,
              created_at timestamp(3) not null, released_at timestamp(3), rider_id varchar(64)
            )
            """).update();

        clock = new MutableClock(NOW);
        presenceStore = new InMemoryDriverPresenceStore(clock, properties.getTracking().getPresenceTtl());
        service = new DriverLocationService(
            repository, presenceStore, new InMemoryFixedWindowRateLimiter(clock), properties, clock);

        tripId = publishTrip("driver-1");
    }

    /* ---- Reporting ---- */

    @Test
    void theTripsDriverMayReportAPosition() {
        DriverLocation stored = service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        assertThat(stored.driverId()).isEqualTo("driver-1");
        assertThat(stored.point().latitude()).isEqualTo(24.4879);
        assertThat(service.watch(tripId, "driver-1")).isPresent();
    }

    @Test
    void anotherDriverMayNotReportOnSomebodyElsesTrip() {
        assertThatThrownBy(() -> service.report(tripId, "driver-2", at(SOFTWARE_PARK, NOW)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("TRIP_NOT_DRIVER"));
    }

    @Test
    void anUnauthenticatedCallerMayNotReport() {
        assertThatThrownBy(() -> service.report(tripId, null, at(SOFTWARE_PARK, NOW)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).status()).isEqualTo(HttpStatus.UNAUTHORIZED));
    }

    @Test
    void convertsAWgs84BrowserFixIntoTheProviderDatum() {
        DriverLocation stored = service.report(tripId, "driver-1", new DriverLocationService.ReportedLocation(
            24.4879, 118.1781, CoordinateDatum.WGS84, null, null, NOW));

        assertThat(stored.point().datum()).isEqualTo(CoordinateDatum.GCJ02);
        // Stored untransformed, the driver would appear ~500m from where they are.
        double shift = Haversine.distanceMeters(
            24.4879, 118.1781, stored.point().latitude(), stored.point().longitude());
        assertThat(shift).isBetween(300.0, 800.0);
    }

    /* ---- Plausibility ---- */

    @Test
    void rejectsAJumpNoVehicleCouldMake() {
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        // ~11km in 10 seconds — roughly 4000 km/h.
        assertThatThrownBy(() -> service.report(tripId, "driver-1", at(JIMEI, NOW.plusSeconds(10))))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("DRIVER_LOCATION_IMPLAUSIBLE"));
    }

    @Test
    void acceptsTheSameDistanceOverAPlausibleInterval() {
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        // The same 11km over 20 minutes is an ordinary drive. Real time advances with it, since a
        // fix dated 20 minutes ahead of the server clock would (rightly) be rejected as skewed.
        clock.advance(Duration.ofSeconds(1_200));
        DriverLocation stored = service.report(tripId, "driver-1", at(JIMEI, NOW.plusSeconds(1_200)));

        assertThat(stored.point().latitude()).isEqualTo(24.5751);
    }

    @Test
    void rejectsATimestampFromTheFuture() {
        assertThatThrownBy(() -> service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW.plusSeconds(600))))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("DRIVER_LOCATION_STALE"));
    }

    @Test
    void rejectsAReplayedTimestampOlderThanThePresenceWindow() {
        assertThatThrownBy(() -> service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW.minusSeconds(600))))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("DRIVER_LOCATION_STALE"));
    }

    @Test
    void rateLimitsFloodedUpdates() {
        int budget = properties.getTracking().getMaxUpdates();
        for (int i = 0; i < budget; i++) {
            service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));
        }

        assertThatThrownBy(() -> service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("DRIVER_LOCATION_RATE_LIMITED"));
    }

    /* ---- Watching ---- */

    @Test
    void aRiderWhoBookedTheTripMaySeeTheDriver() {
        repository.lockSeats(tripId, "order-1", 1, "rider-1");
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        assertThat(service.watch(tripId, "rider-1")).isPresent();
    }

    @Test
    void aRiderWhoDidNotBookGetsNotFoundRatherThanForbidden() {
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        // 404, not 403: a 403 would confirm the trip exists and is being tracked.
        assertThatThrownBy(() -> service.watch(tripId, "rider-stranger"))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).status()).isEqualTo(HttpStatus.NOT_FOUND));
    }

    @Test
    void releasingTheSeatEndsLocationAccess() {
        repository.lockSeats(tripId, "order-1", 1, "rider-1");
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));
        assertThat(service.watch(tripId, "rider-1")).isPresent();

        repository.releaseSeats(tripId, "order-1");

        assertThatThrownBy(() -> service.watch(tripId, "rider-1"))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).status()).isEqualTo(HttpStatus.NOT_FOUND));
    }

    @Test
    void aStalePositionIsReportedAsAbsentNotAsLive() {
        repository.lockSeats(tripId, "order-1", 1, "rider-1");
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        clock.advance(properties.getTracking().getPresenceTtl().plusSeconds(5));

        assertThat(service.watch(tripId, "rider-1")).isEmpty();
    }

    @Test
    void theDriverMayStopSharingImmediately() {
        repository.lockSeats(tripId, "order-1", 1, "rider-1");
        service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW));

        service.stopSharing(tripId, "driver-1");

        assertThat(service.watch(tripId, "rider-1")).isEmpty();
    }

    @Test
    void onlyTheDriverMayStopSharing() {
        repository.lockSeats(tripId, "order-1", 1, "rider-1");

        assertThatThrownBy(() -> service.stopSharing(tripId, "rider-1"))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("TRIP_NOT_DRIVER"));
    }

    @Test
    void anUnknownTripIsNotFound() {
        assertThatThrownBy(() -> service.watch("trip-does-not-exist", "driver-1"))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).status()).isEqualTo(HttpStatus.NOT_FOUND));
    }

    @Test
    void aCancelledTripCannotBeTracked() {
        jdbcClient.sql("update trips set status = 'CANCELLED' where trip_id = :id").param("id", tripId).update();

        assertThatThrownBy(() -> service.report(tripId, "driver-1", at(SOFTWARE_PARK, NOW)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("TRIP_NOT_TRACKABLE"));
    }

    private DriverLocationService.ReportedLocation at(GeoPoint point, Instant capturedAt) {
        return new DriverLocationService.ReportedLocation(
            point.latitude(), point.longitude(), CoordinateDatum.GCJ02, null, null, capturedAt);
    }

    private String publishTrip(String driverId) {
        LocationRef origin = place("软件园三期", SOFTWARE_PARK);
        LocationRef destination = place("集美大学", JIMEI);
        return repository.create(new PublishTripCommand(
            driverId, "软件园三期", "集美大学", "厦门", NOW.plusSeconds(3_600), 3, null, origin, destination
        ), new RouteSnapshot("route-1", 20_000, 2_400, "amap-v5", null, origin, destination)).tripId();
    }

    private LocationRef place(String name, GeoPoint point) {
        return new LocationRef(point, "amap", "poi-" + name, "0592", "350211", name, name,
            LocationSource.AUTOCOMPLETE, null, NOW);
    }

    /** Lets a test move time forward to exercise TTL expiry. */
    private static final class MutableClock extends Clock {
        private Instant instant;

        MutableClock(Instant instant) {
            this.instant = instant;
        }

        void advance(Duration amount) {
            instant = instant.plus(amount);
        }

        @Override
        public Instant instant() {
            return instant;
        }

        @Override
        public java.time.ZoneId getZone() {
            return ZoneOffset.UTC;
        }

        @Override
        public Clock withZone(java.time.ZoneId zone) {
            return this;
        }
    }
}
