package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest
@Import({TripRepository.class, TripMatchingProperties.class, TripPublishService.class, TripPublishServiceTest.FakeMapClient.class,
    TripPublishServiceTest.FakeDriverCapabilityClient.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class TripPublishServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripPublishService service;

    @Autowired
    private FakeMapClient mapClient;

    @Autowired
    private FakeDriverCapabilityClient driverCapabilityClient;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trip_seat_locks").update();
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              idempotency_key varchar(80)
              , origin_lat decimal(10,7)
              , origin_lng decimal(10,7)
              , destination_lat decimal(10,7)
              , destination_lng decimal(10,7)
              , coordinate_datum varchar(16)
              , origin_adcode varchar(16)
              , destination_adcode varchar(16)
              , origin_city_code varchar(16)
              , destination_city_code varchar(16)
              , origin_place_id varchar(64)
              , destination_place_id varchar(64)
              , route_polyline clob
            )
            """).update();
        jdbcClient.sql("""
            create table trip_seat_locks (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null,
              order_id varchar(64) not null unique,
              seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              released_at timestamp(3),
              rider_id varchar(64)
            )
            """).update();
        mapClient.route = new RouteSnapshot("route-authoritative", 22_500, 2_600, "amap-v5");
        mapClient.failure = null;
        mapClient.calls = 0;
        driverCapabilityClient.identityApproved = true;
        driverCapabilityClient.documentsApproved = true;
    }

    @Test
    void publishesTripUsingMapRouteAsPricingAuthority() {
        TripOffer trip = service.publish(command("driver-001", null));

        assertThat(mapClient.origin).isEqualTo("软件园三期");
        assertThat(mapClient.destination).isEqualTo("集美大学");
        assertThat(mapClient.city).isEqualTo("厦门");
        assertThat(trip.route().routeId()).isEqualTo("route-authoritative");
        assertThat(trip.route().distanceMeters()).isEqualTo(22_500);
        assertThat(trip.seatPrice().amount()).isEqualByComparingTo("33.00");
        assertThat(trip.driverId()).isEqualTo("driver-001");
    }

    @Test
    void doesNotCreateTripWhenMapRouteQuoteFails() {
        mapClient.failure = new BusinessException(HttpStatus.BAD_GATEWAY, "MAP_ROUTE_QUOTE_FAILED", "amap route quote failed");

        assertThatThrownBy(() -> service.publish(command("driver-001", null)))
            .isInstanceOf(BusinessException.class);

        assertThat(jdbcClient.sql("select count(*) from trips").query(Long.class).single()).isZero();
    }

    @Test
    void refusesToPublishWithoutApprovedDriverDocuments() {
        driverCapabilityClient.documentsApproved = false;

        assertThatThrownBy(() -> service.publish(command("driver-001", null)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("DRIVER_NOT_APPROVED"));

        assertThat(jdbcClient.sql("select count(*) from trips").query(Long.class).single()).isZero();
        // The capability gate runs before the provider call, so a rejected publish costs no quota.
        assertThat(mapClient.calls).isZero();
    }

    @Test
    void refusesToPublishWithoutApprovedRealNameIdentity() {
        driverCapabilityClient.identityApproved = false;

        assertThatThrownBy(() -> service.publish(command("driver-001", null)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("DRIVER_NOT_APPROVED"));
        assertThat(mapClient.calls).isZero();
    }

    @Test
    void checksCapabilityAgainstThePublishingPrincipal() {
        service.publish(command("driver-042", null));

        assertThat(driverCapabilityClient.lastCheckedUserId).isEqualTo("driver-042");
    }

    @Test
    void repeatedPublishWithTheSameIdempotencyKeyReturnsTheOriginalTrip() {
        TripOffer first = service.publish(command("driver-001", "publish-001"));
        TripOffer second = service.publish(command("driver-001", "publish-001"));

        assertThat(second.tripId()).isEqualTo(first.tripId());
        assertThat(jdbcClient.sql("select count(*) from trips").query(Long.class).single()).isEqualTo(1);
        // A retry must not burn a second provider route quote.
        assertThat(mapClient.calls).isEqualTo(1);
    }

    @Test
    void differentDriversMayReuseTheSameIdempotencyKey() {
        service.publish(command("driver-001", "publish-001"));
        service.publish(command("driver-002", "publish-001"));

        assertThat(jdbcClient.sql("select count(*) from trips").query(Long.class).single()).isEqualTo(2);
    }

    private PublishTripCommand command(String driverId, String idempotencyKey) {
        return PublishTripCommand.ofText(
            driverId,
            "软件园三期",
            "集美大学",
            "厦门",
            Instant.parse("2026-06-24T11:00:00Z"),
            3,
            idempotencyKey
        );
    }

    static class FakeMapClient implements MapClient {
        RouteSnapshot route;
        RuntimeException failure;
        String origin;
        String destination;
        String city;
        int calls;
        boolean structured;

        @Override
        public RouteSnapshot quoteRoute(String origin, String destination, String city) {
            this.origin = origin;
            this.destination = destination;
            this.city = city;
            this.calls++;
            if (failure != null) {
                throw failure;
            }
            return route;
        }

        @Override
        public RouteSnapshot quoteRoute(
            com.o2o.carpooling.common.domain.LocationRef origin,
            com.o2o.carpooling.common.domain.LocationRef destination
        ) {
            this.structured = true;
            this.origin = origin.displayName();
            this.destination = destination.displayName();
            this.calls++;
            if (failure != null) {
                throw failure;
            }
            return route;
        }
    }

    static class FakeDriverCapabilityClient implements DriverCapabilityClient {
        boolean identityApproved = true;
        boolean documentsApproved = true;
        String lastCheckedUserId;

        @Override
        public DriverCapability capability(String userId) {
            lastCheckedUserId = userId;
            return new DriverCapability(
                userId, identityApproved && documentsApproved, identityApproved, documentsApproved);
        }
    }
}
