package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.GeoPoint;
import com.o2o.carpooling.common.domain.LocationRef;
import com.o2o.carpooling.common.domain.LocationSource;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.TripOffer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Duration;
import java.time.Instant;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Geographic matching. Deliberately exercises four unrelated cities: the old substring search
 * only ever worked for the one route it was demoed with, and nothing here may be tuned to a region.
 */
@JdbcTest
@Import({TripRepository.class, TripMatchingProperties.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class TripProximitySearchTest {

    private static final Instant NOON = Instant.parse("2026-08-01T04:00:00Z");

    // 厦门
    private static final GeoPoint SOFTWARE_PARK = GeoPoint.gcj02(24.4879, 118.1781);
    private static final GeoPoint JIMEI_UNIVERSITY = GeoPoint.gcj02(24.5751, 118.0972);
    // 北京
    private static final GeoPoint ZHONGGUANCUN = GeoPoint.gcj02(39.9847, 116.3070);
    private static final GeoPoint BEIJING_SOUTH = GeoPoint.gcj02(39.8654, 116.3786);
    // 成都
    private static final GeoPoint TIANFU_SQUARE = GeoPoint.gcj02(30.6570, 104.0657);
    private static final GeoPoint CHENGDU_EAST = GeoPoint.gcj02(30.6300, 104.1414);
    // 哈尔滨 — high latitude, where the longitude bounding box must widen
    private static final GeoPoint HARBIN_WEST = GeoPoint.gcj02(45.7010, 126.5580);
    private static final GeoPoint CENTRAL_STREET = GeoPoint.gcj02(45.7732, 126.6174);

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripRepository repository;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trip_seat_locks").update();
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              idempotency_key varchar(80),
              origin_lat decimal(10,7),
              origin_lng decimal(10,7),
              destination_lat decimal(10,7),
              destination_lng decimal(10,7),
              coordinate_datum varchar(16),
              origin_adcode varchar(16),
              destination_adcode varchar(16),
              origin_city_code varchar(16),
              destination_city_code varchar(16),
              origin_place_id varchar(64),
              destination_place_id varchar(64),
              route_polyline clob,
              base_fare decimal(10,2), included_km decimal(7,3), per_km_fare decimal(10,2), min_fare decimal(10,2),
              source varchar(16) not null default 'USER'
            )
            """).update();
        jdbcClient.sql("""
            create table trip_seat_locks (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null,
              order_id varchar(64) not null unique,
              seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              released_at timestamp(3),
              rider_id varchar(64)
            )
            """).update();
    }

    @Test
    void findsTripsInEveryCityWithNoCitySpecificCode() {
        publish("xiamen", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON);
        publish("beijing", ZHONGGUANCUN, BEIJING_SOUTH, "110108", NOON);
        publish("chengdu", TIANFU_SQUARE, CHENGDU_EAST, "510105", NOON);
        publish("harbin", HARBIN_WEST, CENTRAL_STREET, "230103", NOON);

        assertThat(ids(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON))).containsExactly("xiamen");
        assertThat(ids(search(ZHONGGUANCUN, BEIJING_SOUTH, NOON))).containsExactly("beijing");
        assertThat(ids(search(TIANFU_SQUARE, CHENGDU_EAST, NOON))).containsExactly("chengdu");
        assertThat(ids(search(HARBIN_WEST, CENTRAL_STREET, NOON))).containsExactly("harbin");
    }

    @Test
    void doesNotLeakTripsFromOtherCities() {
        publish("beijing", ZHONGGUANCUN, BEIJING_SOUTH, "110108", NOON);

        assertThat(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON)).isEmpty();
    }

    @Test
    void matchesANearbyStartRatherThanRequiringAnExactAddress() {
        // ~1.2km from the trip's origin: well inside the 3km pickup radius.
        GeoPoint downTheRoad = GeoPoint.gcj02(24.4975, 118.1800);
        publish("xiamen", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON);

        assertThat(ids(search(downTheRoad, JIMEI_UNIVERSITY, NOON))).containsExactly("xiamen");
    }

    @Test
    void excludesTripsBeyondThePickupRadius() {
        // 厦门北站 is ~15km from 软件园三期 — far outside the 3km pickup radius.
        publish("xiamen", GeoPoint.gcj02(24.6153, 118.0507), JIMEI_UNIVERSITY, "350211", NOON);

        assertThat(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON)).isEmpty();
    }

    @Test
    void appliesTheDepartureWindow() {
        publish("in-window", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON.plus(Duration.ofMinutes(90)));
        publish("out-of-window", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON.plus(Duration.ofHours(6)));

        assertThat(ids(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON))).containsExactly("in-window");
    }

    @Test
    void ignoresTheTimeWindowWhenTheRiderStatesNoPreference() {
        publish("far-future", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON.plus(Duration.ofDays(3)));

        assertThat(ids(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, null))).containsExactly("far-future");
    }

    @Test
    void excludesTripsWithoutEnoughFreeSeats() {
        String tripId = publish("full", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON);
        repository.lockSeats(tripId, "order-001", 3);   // published with 3 seats

        assertThat(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON)).isEmpty();
    }

    @Test
    void honoursTheRequestedSeatCount() {
        String tripId = publish("two-left", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON);
        repository.lockSeats(tripId, "order-001", 1);   // 2 of 3 remain

        assertThat(repository.searchByProximity(
            new TripSearchQuery(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON, 2))).hasSize(1);
        assertThat(repository.searchByProximity(
            new TripSearchQuery(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON, 3))).isEmpty();
    }

    @Test
    void ranksTheLeastDetourFirst() {
        publish("far", GeoPoint.gcj02(24.5100, 118.1950), JIMEI_UNIVERSITY, "350211", NOON);
        publish("near", GeoPoint.gcj02(24.4885, 118.1785), JIMEI_UNIVERSITY, "350211", NOON);
        publish("middle", GeoPoint.gcj02(24.4975, 118.1800), JIMEI_UNIVERSITY, "350211", NOON);

        assertThat(ids(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON)))
            .containsExactly("near", "middle", "far");
    }

    @Test
    void excludesCancelledAndFinishedTrips() {
        String tripId = publish("cancelled", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON);
        jdbcClient.sql("update trips set status = 'CANCELLED' where trip_id = :id").param("id", tripId).update();

        assertThat(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON)).isEmpty();
    }

    @Test
    void ignoresLegacyTripsThatHaveNoCoordinates() {
        // Rows published before structured locations existed cannot be matched geographically;
        // they must be skipped rather than crash the search.
        String tripId = publish("legacy", SOFTWARE_PARK, JIMEI_UNIVERSITY, "350211", NOON);
        jdbcClient.sql("update trips set origin_lat = null, origin_lng = null where trip_id = :id")
            .param("id", tripId).update();

        assertThat(search(SOFTWARE_PARK, JIMEI_UNIVERSITY, NOON)).isEmpty();
    }

    @Test
    void supportsCrossCityRoutes() {
        publish("xiamen-to-chengdu", SOFTWARE_PARK, TIANFU_SQUARE, "350211", NOON);

        assertThat(ids(search(SOFTWARE_PARK, TIANFU_SQUARE, NOON))).containsExactly("xiamen-to-chengdu");
    }

    private List<TripOffer> search(GeoPoint origin, GeoPoint destination, Instant departAt) {
        return repository.searchByProximity(new TripSearchQuery(origin, destination, departAt, 1));
    }

    private List<String> ids(List<TripOffer> trips) {
        return trips.stream().map(TripOffer::originText).toList();
    }

    /** Publishes a trip whose originText doubles as a label, so assertions read clearly. */
    private String publish(String label, GeoPoint origin, GeoPoint destination, String adcode, Instant departAt) {
        RouteSnapshot route = new RouteSnapshot(
            "route-" + label, 20_000, 2_400, "amap-v5", "polyline",
            place(label, origin, adcode), place(label + "-dest", destination, adcode));
        return repository.create(new PublishTripCommand(
            "driver-" + label, label, label + "-dest", "city",
            departAt, 3, null,
            place(label, origin, adcode), place(label + "-dest", destination, adcode)
        ), route).tripId();
    }

    private LocationRef place(String name, GeoPoint point, String adcode) {
        return new LocationRef(
            point, "amap", "poi-" + name, "0000", adcode, name, name,
            LocationSource.AUTOCOMPLETE, null, NOON);
    }
}
