package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.domain.TripStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest
@Import(TripRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class TripRepositoryTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripRepository repository;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trip_seat_locks").update();
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(120) not null,
              destination_text varchar(120) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null
            )
            """).update();
        jdbcClient.sql("""
            create table trip_seat_locks (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null,
              order_id varchar(64) not null unique,
              seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              released_at timestamp(3)
            )
            """).update();
    }

    @Test
    void publishesSearchesAndLoadsTripWithServerOwnedInventory() {
        TripOffer trip = repository.create(new PublishTripCommand(
            "driver-001",
            "软件园三期",
            "集美大学",
            Instant.parse("2026-06-23T11:00:00Z"),
            18_500,
            2_100,
            3
        ));

        List<TripOffer> found = repository.search("软件园", "集美");
        TripOffer loaded = repository.findByTripId(trip.tripId()).orElseThrow();

        assertThat(found).extracting(TripOffer::tripId).containsExactly(trip.tripId());
        assertThat(loaded.status()).isEqualTo(TripStatus.PUBLISHED);
        assertThat(loaded.inventory().totalSeats()).isEqualTo(3);
        assertThat(loaded.inventory().lockedSeats()).isZero();
        assertThat(loaded.seatPrice().amount()).isEqualByComparingTo("28.20");
    }

    @Test
    void locksAndReleasesSeatsIdempotentlyByOrderId() {
        TripOffer trip = repository.create(new PublishTripCommand(
            "driver-001",
            "软件园三期",
            "集美大学",
            Instant.parse("2026-06-23T11:00:00Z"),
            18_500,
            2_100,
            3
        ));

        TripOffer locked = repository.lockSeats(trip.tripId(), "order-001", 2);
        TripOffer duplicate = repository.lockSeats(trip.tripId(), "order-001", 2);
        TripOffer released = repository.releaseSeats(trip.tripId(), "order-001");
        TripOffer duplicateRelease = repository.releaseSeats(trip.tripId(), "order-001");

        assertThat(locked.inventory().lockedSeats()).isEqualTo(2);
        assertThat(duplicate.inventory().lockedSeats()).isEqualTo(2);
        assertThat(released.inventory().lockedSeats()).isZero();
        assertThat(duplicateRelease.inventory().lockedSeats()).isZero();
    }

    @Test
    void rejectsSeatLockWhenInventoryIsInsufficient() {
        TripOffer trip = repository.create(new PublishTripCommand(
            "driver-001",
            "软件园三期",
            "集美大学",
            Instant.parse("2026-06-23T11:00:00Z"),
            18_500,
            2_100,
            1
        ));

        repository.lockSeats(trip.tripId(), "order-001", 1);

        assertThatThrownBy(() -> repository.lockSeats(trip.tripId(), "order-002", 1))
            .isInstanceOf(IllegalStateException.class)
            .hasMessageContaining("not enough seats");
    }
}
