package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.TripOffer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({TripRepository.class, TripMatchingProperties.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class TripDepartureReminderServiceTest {

    private static final Instant NOW = Instant.parse("2026-07-01T02:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripRepository repository;

    @Autowired
    private TripMatchingProperties properties;

    private final CapturingNotificationClient notificationClient = new CapturingNotificationClient();
    private TripDepartureReminderService service;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trip_seat_locks").update();
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              idempotency_key varchar(80),
              origin_lat decimal(10,7),
              origin_lng decimal(10,7),
              destination_lat decimal(10,7),
              destination_lng decimal(10,7),
              coordinate_datum varchar(16),
              origin_adcode varchar(16),
              destination_adcode varchar(16),
              origin_city_code varchar(16),
              destination_city_code varchar(16),
              origin_place_id varchar(64),
              destination_place_id varchar(64),
              route_polyline clob,
              base_fare decimal(10,2), included_km decimal(7,3), per_km_fare decimal(10,2), min_fare decimal(10,2),
              source varchar(16) not null default 'USER',
              departure_reminder_sent_at timestamp(3)
            )
            """).update();
        jdbcClient.sql("""
            create table trip_seat_locks (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null,
              order_id varchar(64) not null unique,
              seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              released_at timestamp(3),
              rider_id varchar(64)
            )
            """).update();
        notificationClient.requests.clear();
        notificationClient.failNext = false;
        service = new TripDepartureReminderService(repository, notificationClient, properties,
            Clock.fixed(NOW, ZoneOffset.UTC));
    }

    private TripOffer publishTrip(Instant departureAt) {
        return repository.create(PublishTripCommand.ofText(
            "driver-001", "软件园三期", "集美大学", "厦门", departureAt, 3, null
        ), new RouteSnapshot("route-001", 18_500, 2_100, "amap-mock"));
    }

    @Test
    void remindsDriverAndLockedRidersOnceWithinTheLeadWindow() {
        TripOffer trip = publishTrip(NOW.plus(Duration.ofMinutes(20)));
        repository.lockSeats(trip.tripId(), "order-1", 1, "rider-1");
        repository.lockSeats(trip.tripId(), "order-2", 1, "rider-2");

        assertThat(service.remindDue(NOW)).isEqualTo(1);

        assertThat(notificationClient.requests).extracting(NotificationFeignClient.NotifyRequest::userId)
            .containsExactlyInAnyOrder("driver-001", "rider-1", "rider-2");
        assertThat(notificationClient.requests).allSatisfy(request -> {
            assertThat(request.category()).isEqualTo("TRIP_DEPARTURE_REMINDER");
            assertThat(request.linkType()).isEqualTo("TRIP");
            assertThat(request.dedupeKey()).isEqualTo(trip.tripId() + ":" + request.userId() + ":DEPARTURE");
        });
        // Second scan is a no-op: the trip has been marked.
        assertThat(service.remindDue(NOW)).isZero();
        assertThat(notificationClient.requests).hasSize(3);
    }

    @Test
    void ignoresTripsOutsideTheLeadWindowAndReleasedSeats() {
        TripOffer far = publishTrip(NOW.plus(Duration.ofHours(5)));
        repository.lockSeats(far.tripId(), "order-far", 1, "rider-far");
        TripOffer near = publishTrip(NOW.plus(Duration.ofMinutes(10)));
        repository.lockSeats(near.tripId(), "order-near", 1, "rider-near");
        repository.releaseSeats(near.tripId(), "order-near");

        assertThat(service.remindDue(NOW)).isEqualTo(1);

        // Only the near trip fires, and only to its driver: the released rider gets nothing.
        assertThat(notificationClient.requests).extracting(NotificationFeignClient.NotifyRequest::userId)
            .containsExactly("driver-001");
    }

    @Test
    void deliveryFailureLeavesTheTripUnmarkedForRetry() {
        publishTrip(NOW.plus(Duration.ofMinutes(20)));
        notificationClient.failNext = true;

        assertThat(service.remindDue(NOW)).isZero();
        // Next pass retries (dedupe keys make any partial re-send harmless).
        assertThat(service.remindDue(NOW)).isEqualTo(1);
    }

    private static final class CapturingNotificationClient implements NotificationFeignClient {
        final List<NotifyRequest> requests = new ArrayList<>();
        boolean failNext;

        @Override
        public void notify(NotifyRequest request) {
            if (failNext) {
                failNext = false;
                throw new RuntimeException("notification-service unavailable");
            }
            requests.add(request);
        }
    }
}
