package com.o2o.carpooling.trip;

import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest
@Import({TripRepository.class, TripPublishService.class, TripPublishServiceTest.FakeMapClient.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class TripPublishServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private TripPublishService service;

    @Autowired
    private FakeMapClient mapClient;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists trip_seat_locks").update();
        jdbcClient.sql("drop table if exists trips").update();
        jdbcClient.sql("""
            create table trips (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null unique,
              driver_id varchar(64) not null,
              origin_text varchar(120) not null,
              destination_text varchar(120) not null,
              departure_at timestamp(3) not null,
              route_id varchar(64) not null,
              distance_meters int not null,
              duration_seconds int not null,
              route_provider varchar(64) not null,
              seat_price_amount decimal(12, 2) not null,
              seat_price_currency varchar(8) not null,
              total_seats int not null,
              locked_seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null
            )
            """).update();
        jdbcClient.sql("""
            create table trip_seat_locks (
              id bigint generated by default as identity primary key,
              trip_id varchar(64) not null,
              order_id varchar(64) not null unique,
              seats int not null,
              status varchar(32) not null,
              created_at timestamp(3) not null,
              released_at timestamp(3)
            )
            """).update();
        mapClient.route = new RouteSnapshot("route-authoritative", 22_500, 2_600, "amap-v5");
        mapClient.failure = null;
    }

    @Test
    void publishesTripUsingMapRouteAsPricingAuthority() {
        TripOffer trip = service.publish(new PublishTripCommand(
            "driver-001",
            "软件园三期",
            "集美大学",
            "厦门",
            Instant.parse("2026-06-24T11:00:00Z"),
            3
        ));

        assertThat(mapClient.origin).isEqualTo("软件园三期");
        assertThat(mapClient.destination).isEqualTo("集美大学");
        assertThat(mapClient.city).isEqualTo("厦门");
        assertThat(trip.route().routeId()).isEqualTo("route-authoritative");
        assertThat(trip.route().distanceMeters()).isEqualTo(22_500);
        assertThat(trip.seatPrice().amount()).isEqualByComparingTo("33.00");
    }

    @Test
    void doesNotCreateTripWhenMapRouteQuoteFails() {
        mapClient.failure = new BusinessException(HttpStatus.BAD_GATEWAY, "MAP_ROUTE_QUOTE_FAILED", "amap route quote failed");

        assertThatThrownBy(() -> service.publish(new PublishTripCommand(
            "driver-001",
            "软件园三期",
            "集美大学",
            "厦门",
            Instant.parse("2026-06-24T11:00:00Z"),
            3
        ))).isInstanceOf(BusinessException.class);

        assertThat(jdbcClient.sql("select count(*) from trips").query(Long.class).single()).isZero();
    }

    static class FakeMapClient implements MapClient {
        RouteSnapshot route;
        RuntimeException failure;
        String origin;
        String destination;
        String city;

        @Override
        public RouteSnapshot quoteRoute(String origin, String destination, String city) {
            this.origin = origin;
            this.destination = destination;
            this.city = city;
            if (failure != null) {
                throw failure;
            }
            return route;
        }
    }
}
