package com.o2o.carpooling.driver;

import com.o2o.carpooling.common.domain.DriverVerificationStatus;
import com.o2o.carpooling.common.domain.OcrResult;
import com.o2o.carpooling.common.domain.VerificationCase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(DriverVerificationRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class DriverVerificationRepositoryTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private DriverVerificationRepository repository;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists driver_verification_cases").update();
        jdbcClient.sql("""
            create table driver_verification_cases (
              id bigint generated by default as identity primary key,
              case_id varchar(64) not null unique,
              user_id varchar(64) not null,
              status varchar(32) not null,
              uploaded_file_ids_json clob not null,
              ocr_result_json clob not null,
              submitted_at timestamp(3) not null,
              reviewed_at timestamp(3),
              reviewer_id varchar(64),
              review_reason varchar(500)
            )
            """).update();
    }

    @Test
    void savesReviewCaseWithMaskedOcrFieldsAndSupportsReviewTransition() {
        VerificationCase verificationCase = new VerificationCase(
            "verify-001",
            "user-001",
            DriverVerificationStatus.OCR_REVIEWABLE,
            Map.of("drivingLicense", "file-driving-license-001", "vehicleLicense", "file-vehicle-license-001"),
            new OcrResult("mock-ocr", 0.91, Map.of("licenseNo", "MOCK-123456", "name", "张三")),
            Instant.parse("2026-06-23T03:00:00Z")
        );

        repository.save(verificationCase);
        repository.updateStatus("verify-001", DriverVerificationStatus.APPROVED);

        VerificationCase stored = repository.findByCaseId("verify-001").orElseThrow();
        String rawOcrJson = jdbcClient.sql("select ocr_result_json from driver_verification_cases where case_id = :caseId")
            .param("caseId", "verify-001")
            .query(String.class)
            .single();

        assertThat(stored.status()).isEqualTo(DriverVerificationStatus.APPROVED);
        assertThat(stored.uploadedFileIds()).containsEntry("drivingLicense", "file-driving-license-001");
        assertThat(stored.ocrResult().fields().get("licenseNo")).doesNotContain("123456").contains("****");
        assertThat(rawOcrJson).doesNotContain("MOCK-123456");
    }
}
