package com.o2o.carpooling.driver;

import com.o2o.carpooling.common.domain.DriverVerificationStatus;
import com.o2o.carpooling.common.domain.OcrResult;
import com.o2o.carpooling.common.domain.VerificationCase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({DriverVerificationRepository.class, DriverVerificationService.class, DriverVerificationController.class, DriverVerificationControllerTest.FakeAuditConfig.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class DriverVerificationControllerTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private DriverVerificationRepository repository;

    @Autowired
    private DriverVerificationController controller;

    @Autowired
    private FakeAuditClient auditClient;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists driver_verification_cases").update();
        jdbcClient.sql("""
            create table driver_verification_cases (
              id bigint generated by default as identity primary key,
              case_id varchar(64) not null unique,
              user_id varchar(64) not null,
              status varchar(32) not null,
              uploaded_file_ids_json clob not null,
              ocr_result_json clob not null,
              submitted_at timestamp(3) not null,
              reviewed_at timestamp(3),
              reviewer_id varchar(64),
              review_reason varchar(500)
            )
            """).update();
        repository.save(new VerificationCase(
            "verify-001",
            "driver-001",
            DriverVerificationStatus.OCR_REVIEWABLE,
            Map.of("drivingLicense", "file-001"),
            new OcrResult("mock-ocr", 0.9, Map.of("licenseNo", "MOCK-123456")),
            Instant.parse("2026-06-23T03:00:00Z")
        ));
        auditClient.actions.clear();
    }

    @Test
    void approveWritesAuditLogWithOperatorActor() {
        VerificationCase approved = controller.approve("operator-001", "verify-001");

        assertThat(approved.status()).isEqualTo(DriverVerificationStatus.APPROVED);
        assertThat(auditClient.actions).containsExactly("DRIVER_VERIFICATION_APPROVED");
    }

    @Configuration
    static class FakeAuditConfig {
        @Bean
        FakeAuditClient fakeAuditClient() {
            return new FakeAuditClient();
        }

        @Bean
        AuditClient auditClient(FakeAuditClient fakeAuditClient) {
            return fakeAuditClient;
        }
    }

    static class FakeAuditClient implements AuditClient {
        final List<String> actions = new ArrayList<>();

        @Override
        public void append(String actorId, String action, String targetType, String targetId, Map<String, String> metadata) {
            actions.add(action);
        }
    }
}
