package com.o2o.carpooling.user;

import com.o2o.carpooling.common.domain.UserAccount;
import com.o2o.carpooling.common.domain.UserRole;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({UserRepository.class, FieldEncryptionService.class})
@TestPropertySource(properties = {
    "spring.flyway.enabled=false",
    "security.field-encryption-key-base64=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
})
class UserRepositoryTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private UserRepository repository;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists users").update();
        jdbcClient.sql("""
            create table users (
              id bigint generated by default as identity primary key,
              user_id varchar(64) not null unique,
              phone varbinary(512) not null,
              roles_json clob not null,
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null
            )
            """).update();
    }

    @Test
    void upsertsUserAndStoresEncryptedPhone() {
        UserAccount user = new UserAccount(
            "user-13800000000",
            "13800000000",
            Set.of(UserRole.RIDER, UserRole.DRIVER),
            Instant.parse("2026-06-23T03:00:00Z")
        );

        repository.upsert(user);

        UserAccount stored = repository.findByUserId("user-13800000000").orElseThrow();
        byte[] rawPhone = jdbcClient.sql("select phone from users where user_id = :userId")
            .param("userId", user.userId())
            .query(byte[].class)
            .single();
        String rolesJson = jdbcClient.sql("select roles_json from users where user_id = :userId")
            .param("userId", user.userId())
            .query(String.class)
            .single();

        assertThat(stored.phone()).isEqualTo("13800000000");
        assertThat(stored.roles()).containsExactlyInAnyOrder(UserRole.RIDER, UserRole.DRIVER);
        assertThat(new String(rawPhone, StandardCharsets.UTF_8)).doesNotContain("13800000000");
        assertThat(rawPhone).hasSizeGreaterThan(32);
        assertThat(rolesJson).contains("RIDER").contains("DRIVER");
    }

    @Test
    void secondUpsertUpdatesInPlaceWithoutTrippingTheUniqueKey() {
        Instant createdAt = Instant.parse("2026-06-23T03:00:00Z");
        repository.upsert(new UserAccount("user-13800000000", "13800000000", Set.of(UserRole.RIDER), createdAt));

        // Re-upsert the same user_id (the promote-to-driver path): must update in place, never insert.
        repository.upsert(new UserAccount("user-13800000000", "13800000000",
            Set.of(UserRole.RIDER, UserRole.DRIVER), createdAt));

        UserAccount stored = repository.findByUserId("user-13800000000").orElseThrow();
        assertThat(stored.roles()).containsExactlyInAnyOrder(UserRole.RIDER, UserRole.DRIVER);
        long rows = jdbcClient.sql("select count(*) from users where user_id = :userId")
            .param("userId", "user-13800000000")
            .query(Long.class)
            .single();
        assertThat(rows).isEqualTo(1);
    }
}
