package com.o2o.carpooling.order;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Duration;
import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

@JdbcTest
@Import(OrderNotificationOutboxRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OrderNotificationOutboxPublisherTest {

    private static final Instant NOW = Instant.parse("2026-07-01T00:00:00Z");

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OrderNotificationOutboxRepository repository;

    private NotificationFeignClient notificationFeignClient;
    private OrderNotificationOutboxPublisher publisher;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists order_notification_outbox").update();
        jdbcClient.sql("""
            create table order_notification_outbox (
              id bigint generated by default as identity primary key,
              event_id varchar(64) not null unique,
              user_id varchar(64) not null,
              category varchar(48) not null,
              title varchar(160) not null,
              body varchar(512) not null,
              link_type varchar(32),
              link_id varchar(64),
              status varchar(32) not null,
              attempts int not null,
              next_attempt_at timestamp(3) not null,
              last_error varchar(512),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              sent_at timestamp(3)
            )
            """).update();
        notificationFeignClient = mock(NotificationFeignClient.class);
        publisher = new OrderNotificationOutboxPublisher(repository, notificationFeignClient);
    }

    @Test
    void deliversPendingEntryWithEventIdAsDedupeKeyAndMarksSent() {
        repository.enqueue("rider-1", "ORDER_PAID", "支付成功", "订单已支付", "ORDER", "order-1", NOW);

        int sent = publisher.publishDue(NOW);

        assertThat(sent).isEqualTo(1);
        ArgumentCaptor<NotificationFeignClient.NotifyRequest> captor =
            ArgumentCaptor.forClass(NotificationFeignClient.NotifyRequest.class);
        verify(notificationFeignClient).notify(captor.capture());
        NotificationFeignClient.NotifyRequest request = captor.getValue();
        assertThat(request.userId()).isEqualTo("rider-1");
        assertThat(request.category()).isEqualTo("ORDER_PAID");
        assertThat(request.linkType()).isEqualTo("ORDER");
        assertThat(request.linkId()).isEqualTo("order-1");
        // The outbox event id is the receiver-side dedupe key: at-least-once relay, exactly-once inbox.
        assertThat(request.dedupeKey()).startsWith("ntf-evt-");
        assertThat(repository.findSendable(NOW.plus(Duration.ofMinutes(5)), 10)).isEmpty();
    }

    @Test
    void failedDeliveryStaysPendingWithBackoffAndRetries() {
        repository.enqueue("rider-1", "ORDER_CREATED", "订单已创建", "请尽快支付", "ORDER", "order-1", NOW);
        doThrow(new RuntimeException("boom")).when(notificationFeignClient).notify(any());

        assertThat(publisher.publishDue(NOW)).isZero();
        // Not yet due again right away…
        assertThat(repository.findSendable(NOW.plusSeconds(1), 10)).isEmpty();
        // …but due after the backoff, with the attempt recorded.
        var retry = repository.findSendable(NOW.plus(Duration.ofSeconds(31)), 10);
        assertThat(retry).hasSize(1);
        assertThat(retry.get(0).attempts()).isEqualTo(1);
    }
}
