package com.o2o.carpooling.order;

import com.o2o.carpooling.common.domain.Money;
import com.o2o.carpooling.common.domain.OrderDetail;
import com.o2o.carpooling.common.domain.OrderStatus;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.SeatInventory;
import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.domain.TripStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest
@Import({OrderRepository.class, OrderService.class, OrderServiceTest.FakeTripClientConfig.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OrderServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OrderService orderService;

    @Autowired
    private FakeTripClient tripClient;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists orders").update();
        jdbcClient.sql("""
            create table orders (
              id bigint generated by default as identity primary key,
              order_id varchar(64) not null unique,
              trip_id varchar(64) not null,
              rider_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              seats int not null,
              amount decimal(12, 2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              payment_deadline_at timestamp(3) not null,
              paid_at timestamp(3),
              cancelled_at timestamp(3),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              unique (rider_id, idempotency_key)
            )
            """).update();
        tripClient.reset();
    }

    @Test
    void createsOrderWithServerPriceAndIdempotentSeatLock() {
        OrderDetail first = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 2, "idem-001"));
        OrderDetail duplicate = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 2, "idem-001"));

        assertThat(first.orderId()).isEqualTo(duplicate.orderId());
        assertThat(first.amount().amount()).isEqualByComparingTo("56.40");
        assertThat(first.status()).isEqualTo(OrderStatus.PENDING_PAYMENT);
        assertThat(tripClient.lockCalls).isEqualTo(1);
    }

    @Test
    void marksPendingOrderPaidAndRejectsPayAfterTimeout() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail paid = orderService.markPaid(order.orderId());

        assertThat(paid.status()).isEqualTo(OrderStatus.SEAT_LOCKED);
        assertThatThrownBy(() -> orderService.timeout(order.orderId()))
            .isInstanceOf(IllegalStateException.class)
            .hasMessageContaining("cannot timeout");
    }

    @Test
    void timeoutCancelsPendingOrderAndReleasesInventoryOnce() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail timedOut = orderService.timeout(order.orderId());
        OrderDetail duplicate = orderService.timeout(order.orderId());

        assertThat(timedOut.status()).isEqualTo(OrderStatus.TIMEOUT_CANCELLED);
        assertThat(duplicate.status()).isEqualTo(OrderStatus.TIMEOUT_CANCELLED);
        assertThat(tripClient.releaseCalls).isEqualTo(1);
    }

    @Test
    void cancelsOverduePendingOrders() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        jdbcClient.sql("""
            update orders
            set payment_deadline_at = :deadline
            where order_id = :orderId
            """)
            .param("deadline", Instant.parse("2026-06-23T00:00:00Z"))
            .param("orderId", order.orderId())
            .update();

        int cancelled = orderService.cancelOverduePendingOrders(Instant.parse("2026-06-23T00:05:00Z"));

        assertThat(cancelled).isEqualTo(1);
        assertThat(orderService.get(order.orderId()).status()).isEqualTo(OrderStatus.TIMEOUT_CANCELLED);
        assertThat(tripClient.releaseCalls).isEqualTo(1);
    }

    @Configuration
    static class FakeTripClientConfig {
        @Bean
        FakeTripClient fakeTripClient() {
            return new FakeTripClient();
        }

        @Bean
        TripClient tripClient(FakeTripClient fakeTripClient) {
            return fakeTripClient;
        }
    }

    static class FakeTripClient implements TripClient {
        int lockCalls;
        int releaseCalls;

        void reset() {
            lockCalls = 0;
            releaseCalls = 0;
        }

        @Override
        public Optional<TripOffer> findTrip(String tripId) {
            return Optional.of(trip());
        }

        @Override
        public TripOffer lockSeats(String tripId, String orderId, int seats) {
            lockCalls++;
            return trip();
        }

        @Override
        public TripOffer releaseSeats(String tripId, String orderId) {
            releaseCalls++;
            return trip();
        }

        private TripOffer trip() {
            return new TripOffer(
                "trip-001",
                "driver-001",
                "软件园三期",
                "集美大学",
                Instant.parse("2026-06-23T11:00:00Z"),
                new RouteSnapshot("route-001", 18_500, 2_100, "amap-mock"),
                new SeatInventory("trip-001", 3, 0),
                new Money(new BigDecimal("28.20"), "CNY"),
                TripStatus.PUBLISHED
            );
        }
    }
}
