package com.o2o.carpooling.order;

import com.o2o.carpooling.common.domain.Money;
import com.o2o.carpooling.common.domain.NotificationCategory;
import com.o2o.carpooling.common.domain.OrderDetail;
import com.o2o.carpooling.common.domain.OrderStatus;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import com.o2o.carpooling.common.domain.SeatInventory;
import com.o2o.carpooling.common.domain.TripOffer;
import com.o2o.carpooling.common.domain.TripStatus;
import com.o2o.carpooling.common.domain.UserRole;
import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest
@Import({OrderRepository.class, OrderOutboxRepository.class, OrderService.class, OrderServiceTest.FakeTripClientConfig.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OrderServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OrderService orderService;

    @Autowired
    private OrderOutboxRepository outboxRepository;

    @Autowired
    private FakeTripClient tripClient;

    @Autowired
    private FakeAuditClient auditClient;

    @Autowired
    private FakeNotificationClient notificationClient;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists orders").update();
        jdbcClient.sql("drop table if exists order_outbox_events").update();
        jdbcClient.sql("""
            create table orders (
              id bigint generated by default as identity primary key,
              order_id varchar(64) not null unique,
              trip_id varchar(64) not null,
              rider_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              seats int not null,
              amount decimal(12, 2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              payment_deadline_at timestamp(3) not null,
              paid_at timestamp(3),
              cancelled_at timestamp(3),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              unique (rider_id, idempotency_key)
            )
            """).update();
        jdbcClient.sql("""
            create table order_outbox_events (
              id bigint generated by default as identity primary key,
              event_id varchar(64) not null unique,
              aggregate_type varchar(64) not null,
              aggregate_id varchar(64) not null,
              event_type varchar(80) not null,
              routing_key varchar(120) not null,
              payload_json clob not null,
              status varchar(32) not null,
              attempts int not null,
              next_attempt_at timestamp(3) not null,
              last_error varchar(512),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              published_at timestamp(3)
            )
            """).update();
        tripClient.reset();
        auditClient.reset();
        notificationClient.notices.clear();
    }

    @Test
    void createsOrderWithServerPriceAndIdempotentSeatLock() {
        OrderDetail first = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 2, "idem-001"));
        OrderDetail duplicate = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 2, "idem-001"));

        assertThat(first.orderId()).isEqualTo(duplicate.orderId());
        assertThat(first.amount().amount()).isEqualByComparingTo("56.40");
        assertThat(first.status()).isEqualTo(OrderStatus.PENDING_PAYMENT);
        assertThat(tripClient.lockCalls).isEqualTo(1);
        assertThat(outboxRepository.findPublishable(Instant.now().plusSeconds(1), 10)).hasSize(1);
        assertThat(jdbcClient.sql("select count(*) from order_outbox_events")
            .query(Long.class)
            .single()).isEqualTo(1);
    }

    @Test
    void marksPendingOrderPaidAndRejectsPayAfterTimeout() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail paid = orderService.markPaid(order.orderId());

        assertThat(paid.status()).isEqualTo(OrderStatus.SEAT_LOCKED);
        assertThat(auditClient.actions).contains("ORDER_PAID");
        assertThatThrownBy(() -> orderService.timeout(order.orderId()))
            .isInstanceOf(IllegalStateException.class)
            .hasMessageContaining("cannot timeout");
    }

    @Test
    void delayedTimeoutIgnoresPaidOrdersWithoutReleasingInventory() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        orderService.markPaid(order.orderId());

        OrderDetail unchanged = orderService.expireIfPaymentPending(order.orderId());

        assertThat(unchanged.status()).isEqualTo(OrderStatus.SEAT_LOCKED);
        assertThat(tripClient.releaseCalls).isZero();
    }

    @Test
    void timeoutCancelsPendingOrderAndReleasesInventoryOnce() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail timedOut = orderService.timeout(order.orderId());
        OrderDetail duplicate = orderService.timeout(order.orderId());

        assertThat(timedOut.status()).isEqualTo(OrderStatus.TIMEOUT_CANCELLED);
        assertThat(duplicate.status()).isEqualTo(OrderStatus.TIMEOUT_CANCELLED);
        assertThat(tripClient.releaseCalls).isEqualTo(1);
        assertThat(auditClient.actions).containsExactly("ORDER_TIMEOUT");
    }

    @Test
    void cancelsOverduePendingOrders() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        jdbcClient.sql("""
            update orders
            set payment_deadline_at = :deadline
            where order_id = :orderId
            """)
            .param("deadline", Instant.parse("2026-06-23T00:00:00Z"))
            .param("orderId", order.orderId())
            .update();

        int cancelled = orderService.cancelOverduePendingOrders(Instant.parse("2026-06-23T00:05:00Z"));

        assertThat(cancelled).isEqualTo(1);
        assertThat(orderService.get(order.orderId()).status()).isEqualTo(OrderStatus.TIMEOUT_CANCELLED);
        assertThat(tripClient.releaseCalls).isEqualTo(1);
    }

    @Test
    void createNotifiesRiderAndDriverWithDeepLinks() {
        orderService.create(new CreateOrderCommand("trip-001", "rider-001", 2, "idem-001"));

        assertThat(notificationClient.categoriesFor("rider-001")).containsExactly("ORDER_CREATED");
        assertThat(notificationClient.categoriesFor("driver-001")).containsExactly("TRIP_SEAT_LOCKED");
        FakeNotificationClient.Notice riderNotice = notificationClient.notices.get(0);
        assertThat(riderNotice.linkType()).isEqualTo("ORDER");
        // Idempotent replay creates no duplicate notices.
        orderService.create(new CreateOrderCommand("trip-001", "rider-001", 2, "idem-001"));
        assertThat(notificationClient.notices).hasSize(2);
    }

    @Test
    void markPaidNotifiesBothPartiesOnceEvenWhenRetried() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        notificationClient.notices.clear();

        orderService.markPaid(order.orderId());
        orderService.markPaid(order.orderId());

        assertThat(notificationClient.categoriesFor("rider-001")).containsExactly("ORDER_PAID");
        assertThat(notificationClient.categoriesFor("driver-001")).containsExactly("ORDER_PAID");
    }

    @Test
    void timeoutNotifiesRiderTimeoutAndDriverSeatRelease() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        notificationClient.notices.clear();

        orderService.timeout(order.orderId());
        orderService.timeout(order.orderId());

        assertThat(notificationClient.categoriesFor("rider-001")).containsExactly("ORDER_PAYMENT_TIMEOUT");
        assertThat(notificationClient.categoriesFor("driver-001")).containsExactly("TRIP_SEAT_RELEASED");
    }

    @Test
    void riderCancelNotifiesRiderConfirmationAndDriverNotice() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        notificationClient.notices.clear();

        orderService.cancel(order.orderId(), "rider-001", Set.of(), null);

        assertThat(notificationClient.categoriesFor("rider-001")).containsExactly("ORDER_CANCELLED_BY_USER");
        assertThat(notificationClient.categoriesFor("driver-001")).containsExactly("ORDER_CANCELLED_BY_USER");
    }

    @Test
    void driverCancelNotifiesOnlyTheRider() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        notificationClient.notices.clear();

        orderService.cancel(order.orderId(), "driver-001", Set.of(), null);

        assertThat(notificationClient.categoriesFor("rider-001")).containsExactly("ORDER_CANCELLED_BY_DRIVER");
        assertThat(notificationClient.categoriesFor("driver-001")).isEmpty();
    }

    @Test
    void cancellationNoticesNeverCarryTheFreeTextReason() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        notificationClient.notices.clear();

        orderService.cancel(order.orderId(), "ops-9", Set.of(UserRole.OPERATOR), "乘客投诉司机爽约");

        // The reason goes to the audit trail only; Message Center bodies carry no PII/free text.
        assertThat(notificationClient.categoriesFor("rider-001")).containsExactly("ORDER_CANCELLED_BY_OPERATOR");
        assertThat(notificationClient.categoriesFor("driver-001")).containsExactly("ORDER_CANCELLED_BY_OPERATOR");
    }

    @Test
    void riderCancelsPendingOrderReleasesSeatsAndIsIdempotent() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail cancelled = orderService.cancel(order.orderId(), "rider-001", Set.of(), null);
        OrderDetail again = orderService.cancel(order.orderId(), "rider-001", Set.of(), null);

        assertThat(cancelled.status()).isEqualTo(OrderStatus.USER_CANCELLED);
        assertThat(again.status()).isEqualTo(OrderStatus.USER_CANCELLED);
        assertThat(tripClient.releaseCalls).isEqualTo(1);
        assertThat(auditClient.actions).containsExactly("ORDER_CANCELLED_BY_USER");
    }

    @Test
    void driverCancelsOrder() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail cancelled = orderService.cancel(order.orderId(), "driver-001", Set.of(), null);

        assertThat(cancelled.status()).isEqualTo(OrderStatus.DRIVER_CANCELLED);
        assertThat(tripClient.releaseCalls).isEqualTo(1);
    }

    @Test
    void operatorCancelsOrderByRole() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail cancelled = orderService.cancel(order.orderId(), "ops-9", Set.of(UserRole.OPERATOR), null);

        assertThat(cancelled.status()).isEqualTo(OrderStatus.OPERATOR_CANCELLED);
    }

    @Test
    void operatorCancelWithReasonRecordsAuditMetadata() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        OrderDetail cancelled = orderService.cancel(order.orderId(), "ops-9", Set.of(UserRole.OPERATOR), " 乘客投诉司机爽约 ");

        assertThat(cancelled.status()).isEqualTo(OrderStatus.OPERATOR_CANCELLED);
        assertThat(auditClient.actions).containsExactly("ORDER_CANCELLED_BY_OPERATOR");
        assertThat(auditClient.metadatas.get(0))
            .containsEntry("cancelledBy", "OPERATOR")
            .containsEntry("reason", "乘客投诉司机爽约");
    }

    @Test
    void cancelReasonOver200CharsIsRejected() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        assertThatThrownBy(() -> orderService.cancel(order.orderId(), "ops-9", Set.of(UserRole.OPERATOR), "长".repeat(201)))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("ORDER_CANCEL_REASON_TOO_LONG"));
        assertThat(orderService.get(order.orderId()).status()).isEqualTo(OrderStatus.PENDING_PAYMENT);
        assertThat(tripClient.releaseCalls).isZero();
    }

    @Test
    void strangerCannotCancelOrder() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        assertThatThrownBy(() -> orderService.cancel(order.orderId(), "intruder", Set.of(), null))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("ORDER_CANCEL_FORBIDDEN"));
        assertThat(orderService.get(order.orderId()).status()).isEqualTo(OrderStatus.PENDING_PAYMENT);
        assertThat(tripClient.releaseCalls).isZero();
    }

    @Test
    void driverCompletesPaidOrderWithoutReleasingSeats() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        orderService.markPaid(order.orderId());

        OrderDetail completed = orderService.complete(order.orderId(), "driver-001", Set.of());

        assertThat(completed.status()).isEqualTo(OrderStatus.COMPLETED);
        assertThat(tripClient.releaseCalls).isZero();
        assertThat(auditClient.actions).containsExactly("ORDER_PAID", "ORDER_COMPLETED");
        // Rider hears about completion + review invite; both deep-link to the order.
        assertThat(notificationClient.categoriesFor("rider-001"))
            .containsSubsequence("ORDER_COMPLETED", "ORDER_REVIEW_INVITATION");
    }

    @Test
    void riderCannotCompleteOrder() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));
        orderService.markPaid(order.orderId());

        assertThatThrownBy(() -> orderService.complete(order.orderId(), "rider-001", Set.of()))
            .isInstanceOf(BusinessException.class)
            .satisfies(ex -> assertThat(((BusinessException) ex).errorCode()).isEqualTo("ORDER_COMPLETE_FORBIDDEN"));
        assertThat(orderService.get(order.orderId()).status()).isEqualTo(OrderStatus.SEAT_LOCKED);
    }

    @Test
    void cannotCompleteUnpaidOrder() {
        OrderDetail order = orderService.create(new CreateOrderCommand("trip-001", "rider-001", 1, "idem-001"));

        assertThatThrownBy(() -> orderService.complete(order.orderId(), "driver-001", Set.of()))
            .isInstanceOf(IllegalStateException.class)
            .hasMessageContaining("cannot complete");
    }

    @Configuration
    static class FakeTripClientConfig {
        @Bean
        FakeTripClient fakeTripClient() {
            return new FakeTripClient();
        }

        @Bean
        TripClient tripClient(FakeTripClient fakeTripClient) {
            return fakeTripClient;
        }

        @Bean
        FakeAuditClient fakeAuditClient() {
            return new FakeAuditClient();
        }

        @Bean
        AuditClient auditClient(FakeAuditClient fakeAuditClient) {
            return fakeAuditClient;
        }

        @Bean
        FakeNotificationClient fakeNotificationClient() {
            return new FakeNotificationClient();
        }

        @Bean
        NotificationClient notificationClient(FakeNotificationClient fakeNotificationClient) {
            return fakeNotificationClient;
        }
    }

    static class FakeTripClient implements TripClient {
        int lockCalls;
        int releaseCalls;
        String lastLockedRiderId;

        void reset() {
            lockCalls = 0;
            releaseCalls = 0;
            lastLockedRiderId = null;
        }

        @Override
        public Optional<TripOffer> findTrip(String tripId) {
            return Optional.of(trip());
        }

        @Override
        public TripOffer lockSeats(String tripId, String orderId, int seats, String riderId) {
            lockCalls++;
            lastLockedRiderId = riderId;
            return trip();
        }

        @Override
        public TripOffer releaseSeats(String tripId, String orderId) {
            releaseCalls++;
            return trip();
        }

        private TripOffer trip() {
            return new TripOffer(
                "trip-001",
                "driver-001",
                "软件园三期",
                "集美大学",
                Instant.parse("2026-06-23T11:00:00Z"),
                new RouteSnapshot("route-001", 18_500, 2_100, "amap-mock"),
                new SeatInventory("trip-001", 3, 0),
                new Money(new BigDecimal("28.20"), "CNY"),
                TripStatus.PUBLISHED
            );
        }
    }

    static class FakeAuditClient implements AuditClient {
        final List<String> actions = new ArrayList<>();
        final List<Map<String, String>> metadatas = new ArrayList<>();

        void reset() {
            actions.clear();
            metadatas.clear();
        }

        @Override
        public void append(String actorId, String action, String targetType, String targetId, Map<String, String> metadata) {
            actions.add(action);
            metadatas.add(metadata);
        }
    }

    static class FakeNotificationClient implements NotificationClient {
        record Notice(String userId, String category, String linkType, String linkId) {
        }

        final List<Notice> notices = new ArrayList<>();

        List<String> categories() {
            return notices.stream().map(Notice::category).toList();
        }

        List<String> categoriesFor(String userId) {
            return notices.stream().filter(notice -> notice.userId().equals(userId)).map(Notice::category).toList();
        }

        @Override
        public void notify(String userId, NotificationCategory category, String title, String body, String linkType, String linkId) {
            notices.add(new Notice(userId, category.name(), linkType, linkId));
        }
    }
}
