package com.o2o.carpooling.order;

import com.o2o.carpooling.common.domain.OrderStatus;
import com.o2o.carpooling.common.foundation.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@JdbcTest
@Import({OrderRepository.class, OrderReviewRepository.class})
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OrderReviewServiceTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private OrderReviewRepository reviewRepository;

    private final FakeAuditClient auditClient = new FakeAuditClient();
    private OrderReviewService service;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists orders").update();
        jdbcClient.sql("drop table if exists order_reviews").update();
        jdbcClient.sql("""
            create table orders (
              id bigint generated by default as identity primary key,
              order_id varchar(64) not null unique,
              trip_id varchar(64) not null,
              rider_id varchar(64) not null,
              idempotency_key varchar(120) not null,
              seats int not null,
              amount decimal(12, 2) not null,
              currency varchar(8) not null,
              status varchar(32) not null,
              payment_deadline_at timestamp(3) not null,
              paid_at timestamp(3),
              cancelled_at timestamp(3),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              version int not null,
              unique (rider_id, idempotency_key)
            )
            """).update();
        jdbcClient.sql("""
            create table order_reviews (
              id bigint generated by default as identity primary key,
              review_id varchar(64) not null unique,
              order_id varchar(64) not null unique,
              trip_id varchar(64) not null,
              reviewer_id varchar(64) not null,
              rating int not null,
              comment varchar(500),
              created_at timestamp(3) not null
            )
            """).update();
        service = new OrderReviewService(orderRepository, reviewRepository, auditClient);
    }

    @Test
    void submitsReviewForCompletedOrderByRider() {
        seedOrder("order-1", "rider-1", "trip-1", OrderStatus.COMPLETED);

        OrderReview review = service.submit("order-1", "rider-1", 5, "  很准时  ");

        assertThat(review.rating()).isEqualTo(5);
        assertThat(review.comment()).isEqualTo("很准时");
        assertThat(review.tripId()).isEqualTo("trip-1");
        assertThat(service.get("order-1").reviewId()).isEqualTo(review.reviewId());
        assertThat(auditClient.actions).containsExactly("ORDER_REVIEW_SUBMITTED");
    }

    @Test
    void rejectsReviewWhenOrderNotCompleted() {
        seedOrder("order-1", "rider-1", "trip-1", OrderStatus.SEAT_LOCKED);

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.submit("order-1", "rider-1", 5, "x"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("REVIEW_ORDER_NOT_COMPLETED"));
    }

    @Test
    void rejectsReviewByNonRider() {
        seedOrder("order-1", "rider-1", "trip-1", OrderStatus.COMPLETED);

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.submit("order-1", "intruder", 5, "x"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("REVIEW_FORBIDDEN"));
    }

    @Test
    void rejectsInvalidRating() {
        seedOrder("order-1", "rider-1", "trip-1", OrderStatus.COMPLETED);

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.submit("order-1", "rider-1", 6, "x"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("REVIEW_RATING_INVALID"));
    }

    @Test
    void rejectsDuplicateReview() {
        seedOrder("order-1", "rider-1", "trip-1", OrderStatus.COMPLETED);
        service.submit("order-1", "rider-1", 4, "ok");

        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.submit("order-1", "rider-1", 5, "again"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("REVIEW_ALREADY_SUBMITTED"));
    }

    @Test
    void getThrowsWhenNoReview() {
        assertThatExceptionOfType(BusinessException.class)
            .isThrownBy(() -> service.get("order-unknown"))
            .satisfies(ex -> assertThat(ex.errorCode()).isEqualTo("REVIEW_NOT_FOUND"));
    }

    private void seedOrder(String orderId, String riderId, String tripId, OrderStatus status) {
        Instant now = Instant.parse("2026-07-01T00:00:00Z");
        jdbcClient.sql("""
            insert into orders (order_id, trip_id, rider_id, idempotency_key, seats, amount, currency, status,
              payment_deadline_at, created_at, updated_at, version)
            values (:orderId, :tripId, :riderId, :idem, 1, 18.00, 'CNY', :status, :now, :now, :now, 0)
            """)
            .param("orderId", orderId)
            .param("tripId", tripId)
            .param("riderId", riderId)
            .param("idem", "idem-" + orderId)
            .param("status", status.name())
            .param("now", now)
            .update();
    }

    private static final class FakeAuditClient implements AuditClient {
        private final List<String> actions = new ArrayList<>();

        @Override
        public void append(String actorId, String action, String targetType, String targetId, Map<String, String> metadata) {
            actions.add(action);
        }
    }
}
