package com.o2o.carpooling.order;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.amqp.AmqpException;
import org.springframework.amqp.core.Message;
import org.springframework.amqp.core.MessagePostProcessor;
import org.springframework.amqp.rabbit.core.RabbitOperations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Duration;
import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;

@JdbcTest
@Import(OrderOutboxRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class OrderOutboxPublisherTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private OrderOutboxRepository repository;

    private RabbitOperations rabbit;
    private PublishedMessage publishedMessage;
    private OrderOutboxPublisher publisher;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists order_outbox_events").update();
        jdbcClient.sql("""
            create table order_outbox_events (
              id bigint generated by default as identity primary key,
              event_id varchar(64) not null unique,
              aggregate_type varchar(64) not null,
              aggregate_id varchar(64) not null,
              event_type varchar(80) not null,
              routing_key varchar(120) not null,
              payload_json clob not null,
              status varchar(32) not null,
              attempts int not null,
              next_attempt_at timestamp(3) not null,
              last_error varchar(512),
              created_at timestamp(3) not null,
              updated_at timestamp(3) not null,
              published_at timestamp(3)
            )
            """).update();
        rabbit = mock(RabbitOperations.class);
        publishedMessage = new PublishedMessage();
        doAnswer(invocation -> {
            publishedMessage.exchange = invocation.getArgument(0);
            publishedMessage.routingKey = invocation.getArgument(1);
            MessagePostProcessor processor = invocation.getArgument(3);
            Message message = processor.postProcessMessage(new Message(new byte[0]));
            publishedMessage.expiration = message.getMessageProperties().getExpiration();
            return null;
        }).when(rabbit).convertAndSend(any(String.class), any(String.class), any(), any(MessagePostProcessor.class));
        OrderMessagingProperties properties = new OrderMessagingProperties();
        properties.getTimeout().setDelayExchange("order.delay");
        properties.getTimeout().setDelayRoutingKey("order.payment.timeout.requested");
        publisher = new OrderOutboxPublisher(repository, rabbit, new ObjectMapper().findAndRegisterModules(), properties);
    }

    @Test
    void publishesPendingTimeoutEventsAndMarksPublished() {
        Instant now = Instant.parse("2026-06-23T00:00:00Z");
        repository.savePaymentTimeoutRequested("order-001", now.plus(Duration.ofMinutes(15)), now);

        int published = publisher.publishDue(now.plusSeconds(1));

        assertThat(published).isEqualTo(1);
        assertThat(publishedMessage.exchange).isEqualTo("order.delay");
        assertThat(publishedMessage.routingKey).isEqualTo("order.payment.timeout.requested");
        assertThat(publishedMessage.expiration).isEqualTo("899000");
        assertThat(repository.findPublishable(now.plus(Duration.ofHours(1)), 10)).isEmpty();
    }

    @Test
    void recordsFailureAndRetriesWhenNextAttemptIsDue() {
        Instant now = Instant.parse("2026-06-23T00:00:00Z");
        repository.savePaymentTimeoutRequested("order-001", now.plus(Duration.ofMinutes(15)), now);
        doThrow(new AmqpException("rabbit unavailable"))
            .when(rabbit)
            .convertAndSend(eq("order.delay"), eq("order.payment.timeout.requested"), any(), any(MessagePostProcessor.class));

        int published = publisher.publishDue(now.plusSeconds(1));

        assertThat(published).isZero();
        assertThat(repository.findPublishable(now.plusSeconds(1), 10)).isEmpty();
        assertThat(repository.findPublishable(now.plusSeconds(31), 10)).hasSize(1);
        assertThat(jdbcClient.sql("select attempts from order_outbox_events")
            .query(Integer.class)
            .single()).isEqualTo(1);
    }

    static class PublishedMessage {
        String exchange;
        String routingKey;
        String expiration;
    }
}
