package com.o2o.carpooling.map;

import com.o2o.carpooling.common.domain.GeoPoint;
import com.o2o.carpooling.common.domain.LocationRef;
import com.o2o.carpooling.common.domain.LocationSource;
import com.o2o.carpooling.common.domain.RouteSnapshot;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(RouteSnapshotRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class RouteSnapshotRepositoryTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private RouteSnapshotRepository repository;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists route_snapshots").update();
        jdbcClient.sql("""
            create table route_snapshots (
              id bigint generated by default as identity primary key,
              route_id varchar(64) not null unique,
              origin_text varchar(200) not null,
              destination_text varchar(200) not null,
              city varchar(64),
              origin_coordinate varchar(64),
              destination_coordinate varchar(64),
              distance_meters int not null,
              duration_seconds int not null,
              provider varchar(32) not null,
              provider_trace varchar(64) not null,
              provider_response_snapshot clob not null,
              created_at timestamp(3) not null,
              polyline clob,
              coordinate_datum varchar(16),
              origin_adcode varchar(16),
              destination_adcode varchar(16),
              origin_city_code varchar(16),
              destination_city_code varchar(16),
              origin_place_id varchar(64),
              destination_place_id varchar(64),
              cache_key varchar(128)
            )
            """).update();
    }

    @Test
    void savesSanitizedSupplierSnapshot() {
        repository.save(RouteQuoteResult.from(
            RouteQuoteRequest.ofText("软件园三期", "集美大学", "厦门"),
            new RouteSnapshot("route-001", 22_500, 2_600, "amap-v5"),
            "amap-v5",
            "118.178100,24.487900",
            "118.097200,24.575100",
            "{\"status\":\"1\",\"key\":\"secret-key\"}"
        ));

        String snapshot = jdbcClient.sql("select provider_response_snapshot from route_snapshots where route_id = 'route-001'")
            .query(String.class)
            .single();
        String provider = jdbcClient.sql("select provider from route_snapshots where route_id = 'route-001'")
            .query(String.class)
            .single();

        assertThat(provider).isEqualTo("amap-v5");
        assertThat(snapshot).doesNotContain("secret-key");
        assertThat(snapshot).contains("\"key\":\"***\"");
    }

    @Test
    void persistsGeometryAndStructuredEndpointsWhenTheProviderSuppliesThem() {
        repository.save(RouteQuoteResult.from(
            RouteQuoteRequest.ofLocations(place("软件园三期", 24.4879, 118.1781, "350211", "B001"),
                place("集美大学", 24.5751, 118.0972, "350211", "B002")),
            new RouteSnapshot("route-002", 22_500, 2_600, "amap-v5",
                "118.1781,24.4879;118.0972,24.5751",
                place("软件园三期", 24.4879, 118.1781, "350211", "B001"),
                place("集美大学", 24.5751, 118.0972, "350211", "B002")),
            "amap",
            "118.1781,24.4879",
            "118.0972,24.5751",
            "{}"
        ));

        var row = jdbcClient.sql("""
            select polyline, coordinate_datum, origin_adcode, destination_adcode,
                   origin_place_id, cache_key, origin_text
            from route_snapshots where route_id = 'route-002'
            """)
            .query((rs, n) -> new String[] {
                rs.getString("polyline"), rs.getString("coordinate_datum"), rs.getString("origin_adcode"),
                rs.getString("destination_adcode"), rs.getString("origin_place_id"),
                rs.getString("cache_key"), rs.getString("origin_text")
            })
            .single();

        assertThat(row[0]).isEqualTo("118.1781,24.4879;118.0972,24.5751");
        assertThat(row[1]).isEqualTo("GCJ02");
        assertThat(row[2]).isEqualTo("350211");
        assertThat(row[3]).isEqualTo("350211");
        assertThat(row[4]).isEqualTo("B001");
        assertThat(row[5]).isNotNull();
        // Structured quotes persist the resolved display name, not the raw "lng,lat" request text.
        assertThat(row[6]).isEqualTo("软件园三期");
    }

    @Test
    void leavesGeometryColumnsNullForLegacyTextQuotes() {
        repository.save(RouteQuoteResult.from(
            RouteQuoteRequest.ofText("软件园三期", "集美大学", "厦门"),
            new RouteSnapshot("route-003", 18_500, 2_312, "amap-mock"),
            "amap-mock", null, null, "{}"
        ));

        var row = jdbcClient.sql(
            "select polyline, origin_adcode, cache_key from route_snapshots where route_id = 'route-003'")
            .query((rs, n) -> new String[] {
                rs.getString("polyline"), rs.getString("origin_adcode"), rs.getString("cache_key")
            })
            .single();

        assertThat(row).containsOnlyNulls();
    }

    @Test
    void derivesTheSameCacheKeyForNearbyOrigins() {
        // ~30m apart: two riders standing near each other must reuse one cached quote.
        String first = RouteSnapshotRepository.cacheKey(quoteBetween(24.48790, 118.17810));
        String second = RouteSnapshotRepository.cacheKey(quoteBetween(24.48812, 118.17828));
        String farAway = RouteSnapshotRepository.cacheKey(quoteBetween(24.5751, 118.0972));

        assertThat(first).isEqualTo(second);
        assertThat(first).isNotEqualTo(farAway);
    }

    private RouteQuoteResult quoteBetween(double originLat, double originLng) {
        LocationRef origin = place("起点", originLat, originLng, "350211", "B001");
        LocationRef destination = place("集美大学", 24.5751, 118.0972, "350211", "B002");
        return RouteQuoteResult.from(
            RouteQuoteRequest.ofLocations(origin, destination),
            new RouteSnapshot("route-x", 22_500, 2_600, "amap-v5", null, origin, destination),
            "amap", null, null, "{}");
    }

    private static LocationRef place(String name, double lat, double lng, String adcode, String placeId) {
        return new LocationRef(
            GeoPoint.gcj02(lat, lng), "amap", placeId, "0592", adcode, name, name,
            LocationSource.AUTOCOMPLETE, null, Instant.parse("2026-07-20T02:00:00Z"));
    }
}
