package com.o2o.carpooling.map;

import com.o2o.carpooling.common.domain.RouteSnapshot;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(RouteSnapshotRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class RouteSnapshotRepositoryTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private RouteSnapshotRepository repository;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("drop table if exists route_snapshots").update();
        jdbcClient.sql("""
            create table route_snapshots (
              id bigint generated by default as identity primary key,
              route_id varchar(64) not null unique,
              origin_text varchar(120) not null,
              destination_text varchar(120) not null,
              city varchar(64),
              origin_coordinate varchar(64),
              destination_coordinate varchar(64),
              distance_meters int not null,
              duration_seconds int not null,
              provider varchar(32) not null,
              provider_trace varchar(64) not null,
              provider_response_snapshot clob not null,
              created_at timestamp(3) not null
            )
            """).update();
    }

    @Test
    void savesSanitizedSupplierSnapshot() {
        repository.save(RouteQuoteResult.from(
            new RouteQuoteRequest("软件园三期", "集美大学", "厦门"),
            new RouteSnapshot("route-001", 22_500, 2_600, "amap-v5"),
            "amap-v5",
            "118.178100,24.487900",
            "118.097200,24.575100",
            "{\"status\":\"1\",\"key\":\"secret-key\"}"
        ));

        String snapshot = jdbcClient.sql("select provider_response_snapshot from route_snapshots where route_id = 'route-001'")
            .query(String.class)
            .single();
        String provider = jdbcClient.sql("select provider from route_snapshots where route_id = 'route-001'")
            .query(String.class)
            .single();

        assertThat(provider).isEqualTo("amap-v5");
        assertThat(snapshot).doesNotContain("secret-key");
        assertThat(snapshot).contains("\"key\":\"***\"");
    }
}
